import Foundation
import Observation
import SwiftUI

/// One subpath as it is stored in a generated icon resource, before its `d` is
/// parsed. Both families decode into this.
struct HugeiconResourceSubpath: Decodable, Sendable {
    let cap: String?
    let d: String
    let join: String?
    let rule: String?
    let strokeWidth: CGFloat?
}

/// One filled or stroked shape inside a hugeicons glyph, in the unit square the
/// 24x24 viewBox was normalized into.
struct HugeiconSubpath {
    let path: Path
    let evenOdd: Bool
    let stroke: Stroke?

    struct Stroke {
        let width: CGFloat
        let cap: CGLineCap
        let join: CGLineJoin
    }
}

/// The bundled channel glyph geometry.
///
/// The resource is `Sources/GrottoUI/Resources/channel-icons.json`, generated by
/// `bun apps/ios-swift/scripts/generate-channel-icon-paths.ts` from the same
/// curated selection the App's icon catalog uses. It is about 1.8 MiB of path
/// data, so it loads once off the main actor and every glyph's `Path` is parsed
/// on first use and then cached. Until the load finishes — and for any name the
/// catalog does not carry — callers render the default hash.
@MainActor
@Observable
public final class ChannelIconCatalog {
    public static let shared = ChannelIconCatalog()

    @ObservationIgnored private var pathData: [String: [HugeiconResourceSubpath]] = [:]
    @ObservationIgnored private var parsed: [String: [HugeiconSubpath]] = [:]
    /// The only observed property: reading it in `subpaths(for:)` is what makes
    /// a rendered glyph refresh when the catalog finishes loading.
    private var state = LoadState.idle

    private enum LoadState {
        case idle
        case loading
        case loaded
        case failed
    }

    init() {}

    /// Starts the one-time load. Safe to call from every glyph's `task`.
    public func load() {
        guard case .idle = state else { return }
        state = .loading

        Task {
            let decoded = await Self.decodeResource()
            if let decoded {
                pathData = decoded
                state = .loaded
            } else {
                // The hash fallback already covers a missing catalog, so a
                // failed decode stays quiet rather than degrading the chat list.
                state = .failed
            }
        }
    }

    /// The glyph for a stored icon name, or nil while loading, when the name is
    /// unknown, or when its geometry could not be parsed.
    func subpaths(for name: String?) -> [HugeiconSubpath]? {
        guard case .loaded = state, let name, !name.isEmpty else { return nil }
        if let cached = parsed[name] { return cached }
        guard let data = pathData[name] else { return nil }

        let subpaths = data.compactMap(Self.subpath)
        guard !subpaths.isEmpty else { return nil }
        parsed[name] = subpaths
        return subpaths
    }

    private static func subpath(_ resource: HugeiconResourceSubpath) -> HugeiconSubpath? {
        // Hugeicons draws in a 24x24 viewBox; the renderer scales the unit
        // square to whatever box size the surface asked for.
        let path = SVGPathData.path(from: resource.d)
            .applying(CGAffineTransform(scaleX: 1.0 / 24, y: 1.0 / 24))
        guard !path.isEmpty else { return nil }

        return HugeiconSubpath(
            path: path,
            evenOdd: resource.rule == "evenodd",
            stroke: resource.strokeWidth.map { width in
                HugeiconSubpath.Stroke(
                    width: width / 24,
                    cap: resource.cap == "round" ? .round : .butt,
                    join: resource.join == "round" ? .round : .miter
                )
            }
        )
    }

    private static func decodeResource() async -> [String: [HugeiconResourceSubpath]]? {
        await Task.detached(priority: .utility) {
            guard let url = Bundle.module.url(forResource: "channel-icons", withExtension: "json"),
                  let data = try? Data(contentsOf: url, options: .mappedIfSafe),
                  let resource = try? JSONDecoder().decode(Resource.self, from: data)
            else { return nil }
            return resource.icons
        }.value
    }

    private struct Resource: Decodable {
        let icons: [String: [HugeiconResourceSubpath]]
    }

}
