/**
 * Emits the bundled channel icon geometry for the native iPhone app.
 *
 * The curation lives in one place: `apps/website/scripts/generate-channel-icon-catalog.ts`
 * picks the icon families, and this script reads the *names* back out of the
 * catalog it generated. It never re-curates, so the App and the iPhone app can
 * only ever disagree if one of the two generated files is stale.
 *
 * The conversion itself lives in `hugeicon-paths.ts`, shared with the app icon
 * set, so the two families can only ever differ in which names they ask for.
 * These are the solid-rounded pictorial glyphs; app iconography is
 * stroke-rounded and generated by `generate-ui-icon-paths.ts`.
 *
 *   bun apps/ios-swift/scripts/generate-channel-icon-paths.ts
 */
import { readFileSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { convertIcons, report } from './hugeicon-paths.ts';

const iosRoot = join(dirname(fileURLToPath(import.meta.url)), '..');
const repoRoot = join(iosRoot, '../..');
const catalogPath = join(
    repoRoot,
    'apps/website/src/components/chats/channel-icon-catalog.generated.ts'
);
const iconDistPath = join(
    repoRoot,
    'apps/website/node_modules/@hugeicons-pro/core-solid-rounded/dist/esm'
);
const outputPath = join(iosRoot, 'Sources/GrottoUI/Resources/channel-icons.json');

const names = [...readFileSync(catalogPath, 'utf8').matchAll(/name: "([A-Za-z0-9]+)"/gu)].map(
    (match) => match[1]
);

if (names.length === 0) {
    throw new Error(`No icon names found in ${catalogPath}. Regenerate the web catalog first.`);
}

const result = await convertIcons(iconDistPath, names);
writeFileSync(outputPath, `${JSON.stringify({ icons: result.icons, version: 1 })}\n`);

report(outputPath, result, statSync(outputPath).size);
