/**
 * Converts hugeicons SVG elements into the path data the Swift renderer parses.
 *
 * Both generated icon resources go through here, so the App's two icon families
 * — solid-rounded channel glyphs and stroke-rounded app iconography — can only
 * ever differ in which family and which names they ask for, never in how the
 * geometry is converted.
 */
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';

export interface Subpath {
    cap?: string;
    d: string;
    join?: string;
    rule?: 'evenodd';
    strokeWidth?: number;
}

export interface ConversionResult {
    empty: string[];
    icons: Record<string, Subpath[]>;
    skipped: string[];
}

/** Loads and converts every name from one hugeicons family's ESM dist. */
export async function convertIcons(distPath: string, names: string[]): Promise<ConversionResult> {
    const icons: Record<string, Subpath[]> = {};
    const skipped: string[] = [];
    const empty: string[] = [];

    for (const name of [...new Set(names)].sort()) {
        const module = (await import(pathToFileURL(join(distPath, `${name}.js`)).href)) as {
            default: [string, Record<string, string>][];
        };
        const subpaths: Subpath[] = [];

        for (const [tag, props] of module.default) {
            const subpath = convert(tag, props);
            if (subpath) {
                subpaths.push(subpath);
            } else {
                skipped.push(`${name}:${tag}`);
            }
        }

        if (subpaths.length === 0) {
            empty.push(name);
            continue;
        }

        icons[name] = subpaths;
    }

    return { empty, icons, skipped };
}

export function convert(tag: string, props: Record<string, string>): Subpath | null {
    if (tag === 'circle') {
        const cx = Number(props.cx);
        const cy = Number(props.cy);
        const r = Number(props.r);
        if (!(Number.isFinite(cx) && Number.isFinite(cy) && Number.isFinite(r)) || r <= 0) {
            return null;
        }
        // Two half arcs, because a single arc back to its own start point is
        // degenerate in the SVG arc spec.
        return {
            d: round(
                `M${cx - r} ${cy}A${r} ${r} 0 1 0 ${cx + r} ${cy}A${r} ${r} 0 1 0 ${cx - r} ${cy}Z`
            ),
        };
    }

    if (tag === 'rect') {
        const x = Number(props.x);
        const y = Number(props.y);
        const width = Number(props.width);
        const height = Number(props.height);
        const radius = Number(props.rx ?? props.ry ?? 0);
        if (![x, y, width, height, radius].every(Number.isFinite) || width <= 0 || height <= 0) {
            return null;
        }
        const rect: Subpath = { d: round(rectPath(x, y, width, height, radius)) };
        applyStroke(rect, props);
        return rect;
    }

    if (tag !== 'path' || typeof props.d !== 'string') {
        return null;
    }

    const subpath: Subpath = { d: round(props.d) };

    if (props.fillRule === 'evenodd') {
        subpath.rule = 'evenodd';
    }

    applyStroke(subpath, props);

    return subpath;
}

/**
 * A hugeicons element without `fill` is stroked chrome, not a filled shape.
 * Written in place rather than spread so the emitted key order — and therefore
 * the generated bytes — stays what it has always been.
 */
function applyStroke(subpath: Subpath, props: Record<string, string>) {
    if (!props.stroke || props.fill) {
        return;
    }
    subpath.strokeWidth = Number(props.strokeWidth ?? 1);
    if (props.strokeLinecap) {
        subpath.cap = props.strokeLinecap;
    }
    if (props.strokeLinejoin) {
        subpath.join = props.strokeLinejoin;
    }
}

/** A rounded rect as path data, so the Swift renderer only parses `d`. */
function rectPath(x: number, y: number, width: number, height: number, radius: number) {
    const r = Math.min(radius, width / 2, height / 2);
    if (r <= 0) {
        return `M${x} ${y}H${x + width}V${y + height}H${x}Z`;
    }
    return (
        `M${x + r} ${y}H${x + width - r}A${r} ${r} 0 0 1 ${x + width} ${y + r}` +
        `V${y + height - r}A${r} ${r} 0 0 1 ${x + width - r} ${y + height}` +
        `H${x + r}A${r} ${r} 0 0 1 ${x} ${y + height - r}` +
        `V${y + r}A${r} ${r} 0 0 1 ${x + r} ${y}Z`
    );
}

/** Trims coordinate precision the 24pt render can never show. */
export function round(d: string) {
    return d.replace(/-?\d+\.\d+/gu, (value) =>
        String(Number.parseFloat(Number(value).toFixed(3)))
    );
}

export function report(label: string, result: ConversionResult, bytes: number) {
    console.log(`${Object.keys(result.icons).length} icons -> ${label}`);
    console.log(`  ${(bytes / 1024).toFixed(1)} KiB`);
    console.log(
        `  skipped elements: ${result.skipped.length}${result.skipped.length ? ` (${result.skipped.join(', ')})` : ''}`
    );
    console.log(
        `  icons with no renderable geometry: ${result.empty.length}${result.empty.length ? ` (${result.empty.join(', ')})` : ''}`
    );
}
