#!/bin/sh
set -eu
umask 077
set -a
. "/Users/zknicker/srv/grotto/config/server.env"
set +a
export NODE_ENV=production
export GROTTO_ATTACHMENT_ROOT=/Users/zknicker/srv/grotto/data/attachments
export GROTTO_RELEASE_MANIFEST=/Users/zknicker/srv/grotto/current/release.json
export GROTTO_SERVER_PORT=18791
export GROTTO_STATIC_APP_ROOT=/Users/zknicker/srv/grotto/current/share/grotto-server/app
exec /Users/zknicker/srv/grotto/current/bin/grotto-server
