import type { components, operations, paths } from './generated/openapi.d.ts';

export type { components, operations, paths, webhooks } from './generated/openapi.d.ts';

export type GrottoApiComponents = components;
export type GrottoApiPaths = paths;
export type GrottoApiOperations = operations;

export type GrottoApiSchema<Name extends keyof components['schemas']> = components['schemas'][Name];

export type GrottoArtifact = GrottoApiSchema<'ChatArtifact'>;
export type GrottoAgentApiError = GrottoApiSchema<'AgentApiError'>;
export type GrottoAgentChannel = GrottoApiSchema<'AgentChannel'>;
export type GrottoAgentChannelMember = GrottoApiSchema<'AgentChannelMember'>;
export type GrottoAgentChannelMembers = GrottoApiSchema<'AgentChannelMembers'>;
export type GrottoAgentHistoryResponse = GrottoApiSchema<'AgentHistoryResponse'>;
export type GrottoAgentManualSearchResponse = GrottoApiSchema<'AgentManualSearchResponse'>;
export type GrottoAgentManualTopic = GrottoApiSchema<'AgentManualTopic'>;
export type GrottoAgentMessage = GrottoApiSchema<'AgentMessage'>;
export type GrottoAgentSearchResult = GrottoApiSchema<'AgentSearchResult'>;
export type GrottoAgentSearchResultList = GrottoApiSchema<'AgentSearchResultList'>;
export type GrottoAgentSendApiError = GrottoApiSchema<'AgentSendApiError'>;
export type GrottoAgentSendRequest = GrottoApiSchema<'AgentSendRequest'>;
export type GrottoAgentSendResponse = GrottoApiSchema<'AgentSendResponse'>;
export type GrottoAgentActionPrepareRequest = GrottoApiSchema<'AgentActionPrepareRequest'>;
export type GrottoAgentActionPrepareResponse = GrottoApiSchema<'AgentActionPrepareResponse'>;
export type GrottoAgentServerInfo = GrottoApiSchema<'AgentServerInfo'>;
export type GrottoChat = GrottoApiSchema<'Chat'>;
export type GrottoChatEvent = GrottoApiSchema<'ChatEvent'>;
export type GrottoChatMessage = GrottoApiSchema<'ChatMessage'>;
export type GrottoChatMessageReceipt = GrottoApiSchema<'ChatMessageReceipt'>;
export type GrottoChatResponse = GrottoApiSchema<'ChatResponse'>;
export type GrottoChatTimelinePage = GrottoApiSchema<'ChatTimelinePage'>;
export type GrottoClearChatReceipt = GrottoApiSchema<'ClearChatReceipt'>;
export type GrottoCreateChatRequest = GrottoApiSchema<'CreateChatRequest'>;
export type GrottoCreateDeliveryRequest = GrottoApiSchema<'CreateDeliveryRequest'>;
export type GrottoCreateMessageRequest = GrottoApiSchema<'CreateMessageRequest'>;
export type GrottoDeleteResponseReceipt = GrottoApiSchema<'DeleteResponseReceipt'>;
export type GrottoEnsureThreadRequest = GrottoApiSchema<'EnsureThreadRequest'>;
export type GrottoEventList = GrottoApiSchema<'EventList'>;
export type GrottoListChatsResponse = GrottoApiSchema<'ListChatsResponse'>;
export type GrottoListMessagesResponse = GrottoApiSchema<'ListMessagesResponse'>;
export type GrottoListResponsesResponse = GrottoApiSchema<'ListResponsesResponse'>;
export type GrottoMarkReadRequest = GrottoApiSchema<'MarkReadRequest'>;
export type GrottoMessageReaction = GrottoApiSchema<'MessageReaction'>;
export type GrottoMessageTask = GrottoApiSchema<'MessageTask'>;
export type GrottoTaskActor = GrottoApiSchema<'TaskActor'>;
export type GrottoTaskLabel = GrottoApiSchema<'TaskLabel'>;
export type GrottoResponseActivity = GrottoApiSchema<'ResponseActivity'>;
export type GrottoResponseEvidence = GrottoApiSchema<'ResponseEvidence'>;
export type GrottoSetThreadFollowRequest = GrottoApiSchema<'SetThreadFollowRequest'>;
export type GrottoThreadSummary = GrottoApiSchema<'ThreadSummary'>;
export type GrottoTurnPromptEvidence = GrottoApiSchema<'TurnPromptEvidence'>;
export type GrottoTurnFileChange = GrottoApiSchema<'TurnFileChange'>;
export type GrottoTurnFileChangeEvidence = GrottoApiSchema<'TurnFileChangeEvidence'>;
export type GrottoUpsertArtifactRequest = GrottoApiSchema<'UpsertArtifactRequest'>;
export type GrottoUpsertResponseActivityRequest = GrottoApiSchema<'UpsertResponseActivityRequest'>;
export type GrottoUpsertResponseRequest = GrottoApiSchema<'UpsertResponseRequest'>;

export * from './agent.ts';
export * from './agent-activity.ts';
export * from './agent-runner.ts';
export * from './app-protocol.ts';
export * from './attachments.ts';
export * from './avatar.ts';
export * from './avatar-generation.ts';
export * from './chat.ts';
export * from './computer-runtime.ts';
export * from './computer-update.ts';
export * from './development-chat-demos.ts';
export * from './manual.ts';
export * from './mcp.ts';
export * from './membership.ts';
export * from './mentions.ts';
export * from './prepared-actions.ts';
export * from './reminders.ts';
export * from './rich-references.ts';
export * from './runtime/contracts.ts';
export * from './runtime/identity.ts';
export * from './runtime/mcp.ts';
export * from './runtime/model-identity.ts';
export * from './runtime/model-providers.ts';
export * from './runtime/pane-links.ts';
export * from './runtime/routes.ts';
export * from './runtime/runtime-aliases.ts';
export * from './runtime/skill-hub.ts';
export * from './runtime/skills.ts';
export * from './runtime/tool-setup.ts';
export * from './server-events.ts';
export * from './stats.ts';
export * from './task.ts';
export * from './task-shared.ts';
export * from './widgets/contracts.ts';
