/**
 * Seeded design skill for everything agents render: inline visuals, widget
 * fences, and artifact pages. The skill sources are real files beside this
 * module (visuals-skill/) so the design-tuning loop edits markdown, not
 * template literals; bun inlines them at build time. Icons are generated by
 * scripts/generate-visuals-skill-icons.mjs from the app's HugeIcons set.
 *
 * The Chart.js CDN pin taught in design-system.md must match the CSP in the
 * app's visual renderer (apps/website/src/widgets/visual.tsx); update both
 * together.
 */

export {
    defaultVisualsSkill,
    visualsSkillFiles,
    visualsSkillId,
} from '@tavern/agent-workspace';
