import type { components, operations, paths } from './generated/openapi.d.ts';

export type { components, operations, paths, webhooks } from './generated/openapi.d.ts';

export type TavernApiComponents = components;
export type TavernApiPaths = paths;
export type TavernApiOperations = operations;

export type TavernApiSchema<Name extends keyof components['schemas']> = components['schemas'][Name];

export type TavernArtifact = TavernApiSchema<'ChatArtifact'>;
export type TavernAgentApiError = TavernApiSchema<'AgentApiError'>;
export type TavernAgentChannel = TavernApiSchema<'AgentChannel'>;
export type TavernAgentChannelMember = TavernApiSchema<'AgentChannelMember'>;
export type TavernAgentChannelMembers = TavernApiSchema<'AgentChannelMembers'>;
export type TavernAgentHistoryResponse = TavernApiSchema<'AgentHistoryResponse'>;
export type TavernAgentMessage = TavernApiSchema<'AgentMessage'>;
export type TavernAgentSearchResult = TavernApiSchema<'AgentSearchResult'>;
export type TavernAgentSearchResultList = TavernApiSchema<'AgentSearchResultList'>;
export type TavernAgentSendApiError = TavernApiSchema<'AgentSendApiError'>;
export type TavernAgentSendRequest = TavernApiSchema<'AgentSendRequest'>;
export type TavernAgentSendResponse = TavernApiSchema<'AgentSendResponse'>;
export type TavernAgentServerInfo = TavernApiSchema<'AgentServerInfo'>;
export type TavernChat = TavernApiSchema<'Chat'>;
export type TavernChatEvent = TavernApiSchema<'ChatEvent'>;
export type TavernChatMessage = TavernApiSchema<'ChatMessage'>;
export type TavernChatMessageReceipt = TavernApiSchema<'ChatMessageReceipt'>;
export type TavernChatResponse = TavernApiSchema<'ChatResponse'>;
export type TavernChatTimelinePage = TavernApiSchema<'ChatTimelinePage'>;
export type TavernClearChatReceipt = TavernApiSchema<'ClearChatReceipt'>;
export type TavernCreateChatRequest = TavernApiSchema<'CreateChatRequest'>;
export type TavernCreateDeliveryRequest = TavernApiSchema<'CreateDeliveryRequest'>;
export type TavernCreateMessageRequest = TavernApiSchema<'CreateMessageRequest'>;
export type TavernDeleteResponseReceipt = TavernApiSchema<'DeleteResponseReceipt'>;
export type TavernEnsureThreadRequest = TavernApiSchema<'EnsureThreadRequest'>;
export type TavernEventList = TavernApiSchema<'EventList'>;
export type TavernListChatsResponse = TavernApiSchema<'ListChatsResponse'>;
export type TavernListMessagesResponse = TavernApiSchema<'ListMessagesResponse'>;
export type TavernListResponsesResponse = TavernApiSchema<'ListResponsesResponse'>;
export type TavernMarkReadRequest = TavernApiSchema<'MarkReadRequest'>;
export type TavernMessageReaction = TavernApiSchema<'MessageReaction'>;
export type TavernMessageTask = TavernApiSchema<'MessageTask'>;
export type TavernTaskActor = TavernApiSchema<'TaskActor'>;
export type TavernTaskLabel = TavernApiSchema<'TaskLabel'>;
export type TavernResponseActivity = TavernApiSchema<'ResponseActivity'>;
export type TavernResponseEvidence = TavernApiSchema<'ResponseEvidence'>;
export type TavernSetThreadFollowRequest = TavernApiSchema<'SetThreadFollowRequest'>;
export type TavernThreadSummary = TavernApiSchema<'ThreadSummary'>;
export type TavernTurnPromptEvidence = TavernApiSchema<'TurnPromptEvidence'>;
export type TavernTurnFileChange = TavernApiSchema<'TurnFileChange'>;
export type TavernTurnFileChangeEvidence = TavernApiSchema<'TurnFileChangeEvidence'>;
export type TavernUpsertArtifactRequest = TavernApiSchema<'UpsertArtifactRequest'>;
export type TavernUpsertResponseActivityRequest = TavernApiSchema<'UpsertResponseActivityRequest'>;
export type TavernUpsertResponseRequest = TavernApiSchema<'UpsertResponseRequest'>;

export * from './agent-appearance.ts';
export * from './development-chat-demos.ts';
export * from './hosted-chat.ts';
export * from './hosted-membership.ts';
export * from './rich-references.ts';
export * from './runtime/contracts.ts';
export * from './runtime/dev-toolkit.ts';
export * from './runtime/identity.ts';
export * from './runtime/mcp.ts';
export * from './runtime/model-identity.ts';
export * from './runtime/model-providers.ts';
export * from './runtime/pane-links.ts';
export * from './runtime/routes.ts';
export * from './runtime/runtime-aliases.ts';
export * from './runtime/skill-hub.ts';
export * from './runtime/skills.ts';
export * from './runtime/tool-setup.ts';
export * from './widgets/contracts.ts';
