/**
 * Emoji coverage for the channel icon catalog.
 *
 * People reach for a channel icon with an emoji in mind — they search "wave"
 * expecting 👋, or "party" expecting 🎉. The curation rules in
 * `generate-channel-icon-catalog.ts` are shaped around icon *families*, so
 * whole emoji concepts fell out of the catalog (`WavingHand01Icon` has no
 * group word, `Hand` is a denied family) and the ones that survived were only
 * searchable by their export name.
 *
 * This table closes that gap. Every row pairs one hugeicons export with the
 * emoji it stands in for and the words people search it by. The generator
 * force-keeps every icon named here, files it under its group heading, and
 * folds the emoji characters and terms into that entry's keywords — so both
 * "waving hand" and a pasted 👋 find the glyph.
 *
 * Rows are `[icon, emoji, terms]`. `emoji` concatenates every emoji the icon
 * covers. Where hugeicons has no glyph for a concept, the emoji rides on the
 * nearest honest generic (mammals on the paw print, insects on the bug) rather
 * than going unsearchable — a paw print for "koala" beats no result at all.
 *
 * What this table deliberately leaves out, measured against Unicode's
 * fully-qualified emoji set:
 *
 * - Skin-tone, hair, gender, and facing-direction variants collapse onto their
 *   base concept, as do most multi-person family compositions. The words still
 *   search ("woman farmer" finds the tractor); only the exact composed
 *   character misses.
 * - Arrows, media transport buttons, keycaps, alphanumeric badges, math signs,
 *   and bare geometric shapes are UI chrome, not channel identities — the same
 *   families the generator already denies.
 * - Country and subdivision flags have no icon analogue at all.
 * - Four abstract marks (🔰 ➰ ➿ 〽️) name no object worth a glyph.
 */

/** One icon, the emoji it covers, and the words that should find it. */
export type EmojiIconRow = readonly [icon: string, emoji: string, terms: string];

export const emojiIconMap: Readonly<Record<string, readonly EmojiIconRow[]>> = {
    Communication: [
        // Faces
        [
            'GrinningIcon',
            '😀😃😄😁😅',
            'grinning grin smiling face beaming big eyes happy sweat nervous relief',
        ],
        [
            'SmileIcon',
            '🙂☺️😊🙃',
            'smile smiling face slightly happy pleased upside down silly sarcasm',
        ],
        ['HappyIcon', '😄😺', 'happy joy cheerful glad delighted'],
        ['LaughingIcon', '😆🤣😂😹', 'laughing laugh rofl lol tears of joy squinting hilarious'],
        ['WinkingIcon', '😉', 'winking wink flirt playful'],
        ['WinkIcon', '😜😝', 'wink winking face with tongue silly'],
        ['TongueWinkLeftIcon', '😜', 'tongue wink left silly zany'],
        ['TongueWinkRightIcon', '😋', 'tongue wink right savoring food yum delicious'],
        ['TongueIcon', '😛👅', 'tongue face with tongue cheeky taste'],
        ['InLoveIcon', '🥰😍', 'in love smiling face with hearts heart eyes adore crush'],
        [
            'KissingIcon',
            '😗😘😙😚💋😽👄🫦',
            'kissing kiss blowing a mark lips smooch mouth biting lip',
        ],
        [
            'NeutralIcon',
            '😐😑🙂‍↔️🙂‍↕️',
            'neutral expressionless blank straight face poker head shaking nodding yes no',
        ],
        ['MehIcon', '🫤😕', 'meh unsure diagonal mouth indifferent whatever'],
        [
            'SenselessIcon',
            '😶😑🫥😶‍🌫️',
            'senseless speechless no mouth silent blank dotted line invisible face in clouds absent',
        ],
        ['UnamusedIcon', '😒', 'unamused unimpressed side eye annoyed'],
        [
            'DispleasedIcon',
            '😒😤🙎',
            'displeased unhappy triumph steam from nose huffing person pouting sulking',
        ],
        ['AnnoyedIcon', '😤🙄', 'annoyed irritated rolling eyes eye roll exasperated'],
        ['GrimacingIcon', '😬', 'grimacing grimace awkward yikes cringe'],
        ['ConfusedIcon', '😕🤨', 'confused puzzled raised eyebrow skeptical unsure'],
        ['SuspiciousIcon', '😏🤨', 'suspicious smirking smirk sly skeptical'],
        ['FlushedIcon', '😳🥵', 'flushed blushing embarrassed hot face overheated'],
        ['ShockedIcon', '😮😯😲', 'shocked open mouth hushed astonished gasp surprised wow'],
        ['SurpriseIcon', '😲🤯', 'surprise surprised exploding head mind blown amazed'],
        [
            'WorryIcon',
            '😟😰😨😧😱😓',
            'worry worried anxious fearful anguished nervous scared screaming in fear scream downcast sweat panic',
        ],
        [
            'FrownIcon',
            '🙁☹️😦🙍🤦',
            'frown frowning sad downturned person facepalming facepalm exasperated',
        ],
        ['UnhappyIcon', '😞😖😣', 'unhappy disappointed confounded persevering down'],
        ['Sad01Icon', '😔😢🥺', 'sad pensive pleading downcast blue upset'],
        [
            'CryingIcon',
            '😢😭😿🥹🥲',
            'crying cry tears sob loudly weeping holding back smiling with tear bittersweet',
        ],
        ['PensiveIcon', '😔🤔', 'pensive thinking thoughtful reflective hmm'],
        [
            'Relieved01Icon',
            '😌😥😮‍💨',
            'relieved relief calm content sad but exhaling sigh breathe out',
        ],
        ['SleepingIcon', '😴😪', 'sleeping sleepy asleep tired doze nap'],
        ['ZzzIcon', '💤', 'zzz sleep snore nap dream'],
        ['DroolingIcon', '🤤', 'drooling drool hungry craving'],
        [
            'Tired01Icon',
            '😫😩🥱😪🫩',
            'tired weary yawning exhausted fatigue sleepy bags under eyes drained worn out',
        ],
        ['AngryIcon', '😠😡👿💢🤬😾', 'angry anger enraged mad rage furious pouting symbols'],
        [
            'CrazyIcon',
            '🤪🥴🫠🫨🫪',
            'crazy zany woozy wild goofy melting shaking distorted overwhelmed',
        ],
        ['SadDizzyIcon', '😵💫', 'dizzy sad dizzy knocked out stars'],
        ['SmileDizzyIcon', '😵‍💫🥴', 'dizzy spiral eyes woozy disoriented'],
        ['DeadIcon', '😵💀', 'dead knocked out crossed out eyes lifeless'],
        ['VomitingIcon', '🤮🤢', 'vomiting nauseated sick queasy gross throw up'],
        [
            'MedicalMaskIcon',
            '😷🤧🥽',
            'medical mask sick face sneezing ill covid surgical goggles protection',
        ],
        ['NerdIcon', '🤓', 'nerd nerdy geek glasses smart'],
        ['MonocleIcon', '🧐', 'monocle inspect scrutinize investigate curious'],
        ['SunglassesIcon', '😎🕶️', 'sunglasses cool shades sun glasses'],
        ['CowboyHatIcon', '🤠', 'cowboy hat yeehaw western rodeo'],
        ['HatGlassesIcon', '🥸', 'disguised disguise incognito fake nose glasses'],
        [
            'FaceMimicIcon',
            '🤫🤭🫢🤥',
            'shushing quiet secret hand over mouth hush open eyes lying pinocchio oops',
        ],
        [
            'SkullIcon',
            '💀☠️⚰️🪦⚱️🏴‍☠️',
            'skull crossbones dead death bones danger coffin headstone gravestone funeral urn pirate flag jolly roger',
        ],
        ['GhostIcon', '👻', 'ghost boo spooky halloween haunt'],
        ['Alien01Icon', '👽🛸', 'alien ufo extraterrestrial space flying saucer'],
        [
            'MonsterIcon',
            '👾👹👺🦹🧚🧛🧜🧝🧞🧟🧌🫈',
            'monster alien ogre goblin creature space invader supervillain fairy vampire merperson mermaid elf genie zombie troll hairy fantasy',
        ],
        ['Robot01Icon', '🤖', 'robot bot android machine automation'],
        ['JokerIcon', '🤡🃏', 'joker clown jester card wild'],
        ['EvilIcon', '😈🙈🙉🙊', 'evil devil imp horns see hear speak no evil monkey'],
        ['PoopIcon', '💩', 'poop poo pile of poo dung crap'],
        ['AngelIcon', '👼😇', 'angel baby angel halo cherub innocent'],
        // Speech and reactions
        [
            'BubbleChatIcon',
            '💬🗨️👁️‍🗨️🗯️🫯',
            'speech balloon bubble chat message talk comment say eye in anger fight cloud shout',
        ],
        ['ThoughtBubbleIcon', '💭', 'thought balloon thinking idea daydream wonder'],
        ['SpeechIcon', '🗣️', 'speaking head speech talk voice announce say'],
        ['ConversationIcon', '🗨️💬', 'conversation discussion dialogue talk exchange'],
        ['VoiceIcon', '🗣️🎙️', 'voice speak audio talk record'],
        ['HashIcon', '#️⃣', 'hash keycap pound number channel'],
        ['HashtagIcon', '#️⃣', 'hashtag hash tag topic channel'],
        ['AtIcon', '📧', 'at sign mention email address'],
        ['MegaphoneOffIcon', '🔕📵', 'muted silenced no announcement bell slash notifications off'],
        ['SilenceIcon', '🔕🤫🤐', 'silence silent mute quiet hush zipper mouth sealed lips'],
        // Hands and gestures
        [
            'WavingHand01Icon',
            '👋🤚🖐️✋🫱🫲🫡🫷🫸',
            'waving hand wave hello hi bye greeting raised palm high five saluting salute pushing stop',
        ],
        ['ThumbsUpIcon', '👍', 'thumbs up like approve yes good agree lgtm'],
        ['ThumbsDownIcon', '👎', 'thumbs down dislike disapprove no bad reject'],
        ['ThumbsUpDownIcon', '👍👎', 'thumbs up down vote react feedback'],
        [
            'HandsClappingIcon',
            '👏🙌',
            'clapping hands applause clap praise raising hands celebrate bravo',
        ],
        ['Clapping01Icon', '👏', 'clapping applause clap cheer well done'],
        [
            'HandPrayerIcon',
            '🙏☯️🕉️✡️🔯☸️🪯🙇🕍🕎🛐',
            'folded hands prayer please thanks thank you namaste pray yin yang balance taoism harmony om aum hinduism sacred star of david judaism menorah six pointed wheel dharma buddhism dharmachakra khanda sikhism emblem bowing bow apology synagogue place worship faith religion',
        ],
        ['HandshakeIcon', '🤝', 'handshake deal agreement partnership shake hands meet'],
        [
            'HandHeartIcon',
            '🫶🤗🫂',
            'heart hands love care hug open support people hugging embrace comfort',
        ],
        ['HandFistIcon', '✊👊🤛🤜', 'raised fist bump punch power solidarity'],
        ['HandGrabIcon', '🤏🤌', 'pinching hand pinched fingers grab small'],
        [
            'HandMetalIcon',
            '🤘🤟🖖',
            'sign of the horns rock on love you gesture metal vulcan salute live long spock',
        ],
        ['OkFingerIcon', '👌🙆', 'ok hand perfect gesturing ok fine good'],
        [
            'VictoryFinger01Icon',
            '✌️☮️🤞☮️',
            'victory hand peace two fingers win symbol sign harmony crossed luck hope',
        ],
        ['Shaka01Icon', '🤙', 'call me hand shaka hang loose surf'],
        ['LoveKoreanFingerIcon', '🫰', 'finger heart love korean heart cute'],
        ['PointingRight01Icon', '👉🫵👆☝️', 'backhand index pointing right you point up above this'],
        ['PointingLeft01Icon', '👈', 'backhand index pointing left point'],
        ['HandPointingDown01Icon', '👇', 'backhand index pointing down point below'],
        ['DoNotTouch01Icon', '🖕🚫', 'middle finger rude do not touch prohibited'],
        [
            'HandHelpingIcon',
            '🫴🤲👐',
            'palm up hand offering helping support give open hands hug offer',
        ],
        ['HandPlatterIcon', '🫳💁', 'palm down hand tipping hand serving present'],
        // Hearts
        [
            'HeartIcon',
            '❤️🩷🧡💛💚💙🩵💜🤎🖤🩶🤍💗💓💖💞💕💟❣️♥️💘💝',
            'heart love red pink orange yellow green blue purple black white like favorite with arrow cupid ribbon gift',
        ],
        ['HeartbreakIcon', '💔', 'broken heart heartbreak breakup sad split'],
        ['HeartCrackIcon', '💔', 'heart crack broken hurt'],
        ['HeartAddIcon', '❤️‍🩹', 'mending heart healing add favorite'],
        ['MailLove01Icon', '💌', 'love letter valentine romance mail heart'],
        ['ScanHeartIcon', '💓🫀', 'beating heart heartbeat anatomical pulse'],
    ],
    People: [
        ['KeffiyehIcon', '👳', 'person wearing turban headwrap keffiyeh'],
        ['UserIcon', '🧑👤', 'person adult bust in silhouette profile someone'],
        ['UserMultipleIcon', '👥🧑‍🤝‍🧑👫👭👬', 'people busts holding hands group pair together'],
        [
            'UserGroupIcon',
            '👪🧑‍🧑‍🧒🧑‍🧒🧑‍🧑‍🧒‍🧒🧑‍🧒‍🧒👨‍👩‍👦👨‍👩‍👧👩‍👦👩‍👧👨‍👦👨‍👧',
            'family group team community household adults child parent parents children kids',
        ],
        ['TeamWorkIcon', '🤝👥', 'teamwork collaboration together team crew'],
        ['ManIcon', '👨🧔👨‍🦰👨‍🦱👨‍🦳👨‍🦲👱‍♂️', 'man male guy beard hair bald blond'],
        ['WomanIcon', '👩👩‍🦰👩‍🦱👩‍🦳👩‍🦲👱‍♀️🧕', 'woman female lady hair bald blond headscarf'],
        ['ManWomanIcon', '👫💑👩‍❤️‍👨', 'couple woman and man with heart partners relationship'],
        ['Baby01Icon', '👶🚼', 'baby infant newborn child symbol'],
        [
            'InfantIcon',
            '👶🤱👩‍🍼👨‍🍼🧑‍🍼🤰🫃🫄',
            'infant baby feeding breast nursing pregnant pregnancy expecting maternity',
        ],
        ['ChildIcon', '🧒👦👧', 'child kid boy girl young'],
        ['KidIcon', '🧒👦👧', 'kid child youngster youth'],
        ['ElderIcon', '🧓👴👵', 'older person old man old woman elderly senior grandparent'],
        ['WeddingIcon', '💒👰🤵💏', 'wedding marriage bride groom veil tuxedo kiss couple'],
        ['MaskLoveIcon', '💏💑', 'kiss couple with heart romance love'],
        // Roles
        ['Doctor01Icon', '🧑‍⚕️👨‍⚕️👩‍⚕️', 'health worker doctor nurse physician medic'],
        ['StudentIcon', '🧑‍🎓👨‍🎓👩‍🎓', 'student graduate learner pupil scholar'],
        ['StudentsIcon', '🧑‍🎓👨‍🎓👩‍🎓', 'students class cohort learners'],
        ['TeacherIcon', '🧑‍🏫👨‍🏫👩‍🏫', 'teacher instructor professor educator'],
        ['JudgeIcon', '🧑‍⚖️👨‍⚖️👩‍⚖️', 'judge court law justice gavel'],
        ['TractorIcon', '🧑‍🌾👨‍🌾👩‍🌾🚜', 'farmer farming agriculture tractor field farm'],
        ['ChefIcon', '🧑‍🍳👨‍🍳👩‍🍳', 'cook chef kitchen culinary'],
        ['TechnicianIcon', '🧑‍🔧👨‍🔧👩‍🔧', 'mechanic technician repair engineer fix'],
        ['LaborIcon', '🧑‍🏭👨‍🏭👩‍🏭👷', 'factory worker construction worker labor builder'],
        ['ManagerIcon', '🧑‍💼👨‍💼👩‍💼', 'office worker manager executive business boss'],
        ['LabsIcon', '🧑‍🔬👨‍🔬👩‍🔬🥼', 'scientist researcher lab experiment coat laboratory'],
        ['DeveloperIcon', '🧑‍💻👨‍💻👩‍💻', 'technologist developer programmer coder engineer'],
        ['MicVocalIcon', '🧑‍🎤👨‍🎤👩‍🎤', 'singer vocalist performer artist microphone'],
        ['PaintBoardIcon', '🧑‍🎨👨‍🎨👩‍🎨🎨', 'artist painter palette art paint'],
        [
            'AirplaneSeatIcon',
            '🧑‍✈️👨‍✈️👩‍✈️💺',
            'pilot aviator flight crew cabin seat airplane reserved',
        ],
        ['Astronaut01Icon', '🧑‍🚀👨‍🚀👩‍🚀', 'astronaut spaceman cosmonaut space'],
        [
            'FireExtinguisherIcon',
            '🧑‍🚒👨‍🚒👩‍🚒🧯',
            'firefighter fireman extinguisher fire safety emergency',
        ],
        ['PoliceBadgeIcon', '👮🚓', 'police officer cop badge law enforcement'],
        [
            'InvestigationIcon',
            '🕵️🥷',
            'detective investigator spy sleuth investigation ninja stealth shinobi covert',
        ],
        ['Sheriff01Icon', '💂🤺', 'guard sheriff sentry officer'],
        ['MentorIcon', '🧑‍🏫🧙', 'mentor guide coach advisor'],
        ['CrownIcon', '👑🫅🤴👸', 'crown king queen prince princess royal monarch'],
        ['CustomerServiceIcon', '💁🎧', 'customer service support help desk agent tipping hand'],
        ['UserQuestion01Icon', '🤷🙋', 'shrugging shrug raising hand question ask'],
        // Body
        ['BicepsFlexedIcon', '💪🦾', 'flexed biceps muscle strong strength mechanical arm'],
        ['BodyPartMuscleIcon', '💪', 'muscle body part strength fitness'],
        ['BodyPartLegIcon', '🦵🦿', 'leg limb mechanical leg body part'],
        ['FootprintsIcon', '👣🦶', 'footprints foot steps track walk'],
        ['EarIcon', '👂🦻', 'ear hearing listen hearing aid'],
        ['NoseIcon', '👃', 'nose smell scent breathe'],
        ['BrainIcon', '🧠', 'brain mind think intelligence smart'],
        ['LungsIcon', '🫁', 'lungs breathe respiratory organ'],
        ['KidneysIcon', '🫘', 'kidneys organ beans anatomy'],
        ['LiverIcon', '🫀', 'liver organ anatomy'],
        ['DentalToothIcon', '🦷🪥', 'tooth teeth dental dentist toothbrush hygiene brush'],
        ['Bone01Icon', '🦴', 'bone skeleton anatomy'],
        ['EyeIcon', '👁️👀🫣🧿🪬', 'eye eyes look see watch peeking nazar amulet evil hamsa charm'],
        ['FingerPrintIcon', '🫆', 'fingerprint identity biometric touch id'],
        ['SpermIcon', '🧬', 'sperm fertility reproduction'],
        // Activity
        ['WalkingIcon', '🚶🧍', 'person walking standing stroll pedestrian'],
        ['WorkoutRunIcon', '🏃', 'person running run jog sprint marathon'],
        ['Yoga01Icon', '🧘🧎', 'lotus position yoga meditation kneeling calm'],
        ['Bathtub01Icon', '🛀🧖🛁', 'person taking bath steamy room sauna spa bathtub soak wash'],
        ['BedIcon', '🛌🛏️', 'person in bed sleep rest bedroom mattress'],
        [
            'WorkoutGymnasticsIcon',
            '🤸🤾🤹🧗',
            'cartwheeling gymnastics juggling handball acrobatics climbing climb bouldering',
        ],
        ['FlyingHumanIcon', '🕴️🦸', 'levitating superhero flying person in suit'],
        ['HairDryerIcon', '💇💆', 'haircut salon massage barber grooming'],
        [
            'AccessibilityIcon',
            '♿🦽🦼🧑‍🦯👨‍🦯👩‍🦯🧑‍🦼👨‍🦼👩‍🦼🧑‍🦽👨‍🦽👩‍🦽🧏',
            'wheelchair accessibility disabled white cane accessible blind mobility deaf person hard of hearing sign language motorized manual',
        ],
    ],
    Animals: [
        [
            'PawPrintIcon',
            '🐾🐶🐕🦮🐕‍🦺🐩🐺🦊🦝🐯🐅🐆🦁🐻🐻‍❄️🐨🐼🦥🦦🦨🦡🦔🐵🐒🦍🦧🐘🦣🦏🦛🦒🦘🦇',
            'paw prints dog puppy wolf fox raccoon tiger leopard lion bear polar koala panda sloth otter skunk badger hedgehog pet monkey ape gorilla orangutan primate elephant mammoth rhinoceros hippopotamus giraffe tall savanna kangaroo joey marsupial bat nocturnal vampire guide service',
        ],
        ['CatIcon', '🐱🐈🐈‍⬛😺😸😹😻😼😽🙀😿😾', 'cat kitten kitty feline black cat meow'],
        [
            'HorseIcon',
            '🐴🐎🦄🦓🫏🦌🫎🐂🐃🐄🐮🐐🐏🐑🦙🦬',
            'horse pony unicorn zebra donkey deer moose ox buffalo cow goat ram ewe sheep lamb bison herd',
        ],
        ['HorseHeadIcon', '🐴🏇', 'horse head horse racing equestrian'],
        ['RockingHorseIcon', '🎠🐴', 'carousel horse rocking horse merry go round'],
        ['CamelIcon', '🐪🐫🦙', 'camel dromedary two hump llama alpaca desert'],
        ['PandaIcon', '🐼', 'panda bear bamboo'],
        ['RabbitIcon', '🐰🐇', 'rabbit bunny hare hop'],
        ['SquirrelIcon', '🐿️🦫', 'chipmunk squirrel beaver rodent'],
        ['RatIcon', '🐀🐁🐭🐹🪤', 'rat mouse hamster rodent trap catch pest'],
        ['PiggyBankIcon', '🐷🐖🐗🐽💰', 'pig hog boar piggy swine bank savings deposit'],
        [
            'BirdIcon',
            '🐦🐦‍⬛🕊️🦅🦆🦢🦉🦤🦩🦚🦜🪿🐦‍🔥🐧🦃🐔🐓🐣🐤🐥',
            'bird dove eagle duck swan owl dodo flamingo peacock parrot goose phoenix penguin turkey chicken rooster chick',
        ],
        ['FeatherIcon', '🪶🪽', 'feather wing quill plume'],
        ['BirdhouseIcon', '🪹🪺', 'nest empty nest with eggs birdhouse'],
        ['EggIcon', '🥚🪺', 'egg eggs nest shell protein'],
        [
            'TurtleIcon',
            '🐢🐊🦎🐍🐸🐲🐉🦕🦖',
            'turtle tortoise crocodile alligator lizard snake reptile frog toad amphibian ribbit dragon dinosaur sauropod trex fantasy',
        ],
        [
            'FishIcon',
            '🐟🐠🐡🦈🐬🐳🐋🫍🦭',
            'fish tropical blowfish shark dolphin whale orca seal sea',
        ],
        ['FishSymbolIcon', '🐟', 'fish symbol swim aquatic'],
        ['OctopusIcon', '🐙🦑🪼', 'octopus squid jellyfish tentacle'],
        ['ShellIcon', '🐚🪸', 'spiral shell coral seashell beach'],
        ['ShellfishIcon', '🦪🦞', 'oyster lobster shellfish pearl'],
        ['CrabIcon', '🦀', 'crab crustacean claw'],
        ['ShrimpIcon', '🦐', 'shrimp prawn crustacean'],
        ['SnailIcon', '🐌', 'snail slow shell mollusc'],
        [
            'Bug01Icon',
            '🐛🪲🐞🦗🪳🦂🦟🪰🦋🐜🕷️🕸️',
            'bug beetle lady ladybug cricket cockroach scorpion mosquito fly insect butterfly moth wings metamorphosis ant colony worker spider web cobweb arachnid',
        ],
        ['Honey01Icon', '🍯🐝', 'honey pot jar bee sweet honeybee buzz pollinate'],
        ['WormIcon', '🪱', 'worm earthworm larva'],
        ['BacteriaIcon', '🦠', 'microbe bacteria germ virus microorganism'],
        ['DnaIcon', '🧬', 'dna genetics helix genome biology'],
    ],
    Nature: [
        ['BlackHoleIcon', '🕳️', 'hole black hole void gap'],
        [
            'FlowerIcon',
            '🌸💮🌺🌼🏵️🪷🪻🌻',
            'flower cherry blossom hibiscus rosette lotus hyacinth bloom sunflower sun',
        ],
        ['RoseIcon', '🌹🥀', 'rose wilted flower romance thorn'],
        ['TulipIcon', '🌷💐', 'tulip bouquet flowers spring'],
        ['SakuraIcon', '🌸', 'sakura cherry blossom spring japan'],
        ['FlowerPotIcon', '🪴', 'potted plant houseplant pot indoor'],
        ['SproutIcon', '🌱🌿', 'seedling sprout herb grow new plant'],
        ['Plant01Icon', '🌿🪴', 'plant greenery foliage herb'],
        ['Leaf01Icon', '🍃🍂🍁☘️🍀', 'leaf fallen maple shamrock four leaf clover fluttering luck'],
        ['CloverIcon', '🍀☘️', 'clover shamrock lucky four leaf'],
        ['LeafyGreenIcon', '🥬🌿', 'leafy green lettuce cabbage greens'],
        [
            'Tree01Icon',
            '🌳🌲🪾🪵',
            'tree deciduous evergreen leafless forest wood log timber lumber',
        ],
        ['PineTreeIcon', '🌲🎄🎍', 'evergreen pine christmas tree conifer decoration'],
        ['TreePalmIcon', '🌴🏝️', 'palm tree tropical island beach'],
        ['TreesIcon', '🌳🌲🏞️', 'trees forest woods national park'],
        ['CactusIcon', '🌵🏜️', 'cactus desert succulent arid'],
        ['MushroomIcon', '🍄‍🟫', 'mushroom fungus toadstool brown'],
        ['WheatIcon', '🌾', 'sheaf of rice wheat grain harvest'],
        ['EarthIcon', '🌍🌎🌏🌐', 'globe earth world planet europe africa americas asia'],
        ['GlobeIcon', '🌐🗺️', 'globe world map meridians international'],
        ['SaturnIcon', '🪐', 'ringed planet saturn space solar system'],
        [
            'StarIcon',
            '⭐🌟✨🌠🤩',
            'star glowing sparkles shooting favorite struck starry eyed amazed',
        ],
        [
            'SparklesIcon',
            '✨🌟✳️✴️❇️',
            'sparkles shine magic glitter new eight spoked asterisk pointed star sparkle',
        ],
        ['FallingStarIcon', '🌠💫', 'shooting star falling wish dizzy'],
        ['GalaxyIcon', '🌌', 'milky way galaxy space stars cosmos'],
        [
            'MoonIcon',
            '🌙🌛🌜🌚🌝🌑🌒🌓🌔🌕🌖🌗🌘',
            'moon crescent quarter gibbous full new lunar night',
        ],
        ['MoonStarIcon', '🌙⭐', 'moon and star night crescent'],
        ['Sun01Icon', '☀️🌞🔆', 'sun sunny bright daylight clear'],
        ['SunriseIcon', '🌅🌄', 'sunrise dawn morning sun over mountains'],
        ['SunsetIcon', '🌇🌆', 'sunset dusk evening cityscape'],
        ['CloudIcon', '☁️🌫️🌁', 'cloud fog foggy overcast mist'],
        ['SunCloud01Icon', '⛅🌤️🌥️', 'sun behind cloud partly cloudy'],
        ['CloudRainIcon', '🌧️🌦️☔', 'cloud with rain rainy shower umbrella with rain drops'],
        ['CloudLightningIcon', '🌩️⛈️', 'cloud with lightning thunder storm'],
        ['CloudSnowIcon', '🌨️', 'cloud with snow snowy flurries'],
        ['SnowIcon', '❄️🌨️☃️⛄', 'snow snowy winter cold snowman frosty'],
        ['SnowflakeIcon', '❄️🥶', 'snowflake frost winter freeze cold face freezing chilly'],
        ['Tornado01Icon', '🌪️🌀', 'tornado cyclone twister hurricane storm'],
        ['TropicalStormIcon', '🌀🌊', 'tropical storm cyclone hurricane'],
        ['WindIcon', '🌬️💨', 'wind face windy breeze dashing away gust'],
        ['RainbowIcon', '🌈🏳️‍🌈', 'rainbow pride colors arc flag lgbtq'],
        ['UmbrellaIcon', '☂️🌂⛱️', 'umbrella closed parasol rain shade'],
        ['ThermometerIcon', '🌡️🤒', 'thermometer temperature fever heat'],
        ['ZapIcon', '⚡', 'high voltage lightning bolt zap electric power'],
        ['FireIcon', '🔥❤️‍🔥', 'fire flame hot burn lit heat'],
        ['FlameIcon', '🔥🕯️', 'flame fire candle burn'],
        ['DropletIcon', '💧🩸🚰', 'droplet drop water blood liquid potable drinking tap'],
        ['DropletsIcon', '💦🫧🫟', 'sweat droplets bubbles splash water splatter spray'],
        ['WavesIcon', '🌊', 'water wave ocean sea surf tide'],
        [
            'MountainIcon',
            '⛰️🏔️🗻🛘🌋',
            'mountain snow capped mount fuji peak landslide volcano eruption lava magma',
        ],
        ['DesertIcon', '🏜️🌵', 'desert sand dune arid'],
        ['IslandIcon', '🏝️🌴', 'desert island tropical palm'],
        ['BeachIcon', '🏖️⛱️', 'beach with umbrella shore sand coast'],
        ['LakeIcon', '🏞️🌊', 'lake national park water river'],
        ['StoneIcon', '🪨🧱🗿', 'rock stone brick boulder moai easter island statue head'],
        ['Recycle01Icon', '♻️🚮', 'recycling symbol recycle litter bin sustainable'],
        ['EcoEnergyIcon', '🌱♻️', 'eco energy green sustainable renewable'],
        ['Comet01Icon', '☄️', 'comet meteor space tail'],
    ],
    Food: [
        ['GrapesIcon', '🍇', 'grapes vine fruit wine'],
        ['WatermelonIcon', '🍉🍈', 'watermelon melon fruit summer'],
        ['OrangeIcon', '🍊🍋🍋‍🟩', 'tangerine orange lemon lime citrus fruit'],
        ['CitrusIcon', '🍋🍊', 'citrus lemon lime orange zest'],
        ['BananaIcon', '🍌', 'banana fruit potassium'],
        [
            'AppleIcon',
            '🍎🍏🍍🥭🍐🍓🫐🥝🍅🫒',
            'apple red green fruit pineapple mango pear strawberry blueberries kiwi tomato olive',
        ],
        ['CherryIcon', '🍒🍑', 'cherries cherry peach fruit'],
        ['AvocadoIcon', '🥑', 'avocado guacamole fruit'],
        ['MilkCoconutIcon', '🥥🥛', 'coconut milk drink tropical palm'],
        ['CarrotIcon', '🥕🍠', 'carrot vegetable root orange roasted sweet potato yam'],
        ['CornIcon', '🌽', 'ear of corn maize vegetable'],
        ['PepperIcon', '🌶️🫑', 'hot pepper chili bell pepper spicy'],
        ['BroccoliIcon', '🥦', 'broccoli vegetable green'],
        ['BeanIcon', '🫘🥜🫛🌰', 'beans peanuts pea pod chestnut legume'],
        ['SaladIcon', '🥗🥬', 'green salad leafy healthy bowl'],
        [
            'NaturalFoodIcon',
            '🥬🥕🍆🥔🥒🧄🧅🫚🫜',
            'natural food organic fresh produce vegetable eggplant aubergine potato cucumber garlic onion ginger root',
        ],
        ['OrganicFoodIcon', '🌱🥗', 'organic food natural healthy'],
        ['VegetarianFoodIcon', '🥗🥦', 'vegetarian food veggie meatless'],
        ['VeganIcon', '🌱🥬', 'vegan plant based'],
        ['Bread01Icon', '🍞🥖🫓🥯', 'bread baguette flatbread bagel loaf bakery'],
        ['KnifeBreadIcon', '🥖🔪', 'bread knife slice bakery'],
        ['CroissantIcon', '🥐🥨🧇', 'croissant pretzel pastry bakery waffle breakfast batter'],
        ['CinnamonRollIcon', '🥐🍩', 'cinnamon roll pastry sweet bun'],
        ['CheeseIcon', '🧀🧈', 'cheese wedge dairy butter spread'],
        ['BeefIcon', '🥩🍖', 'cut of meat beef meat on bone'],
        ['SteakIcon', '🥩', 'steak beef grill meat'],
        ['DrumstickIcon', '🍗🦴', 'poultry leg drumstick chicken'],
        ['ChickenThighsIcon', '🍗🐔', 'chicken thighs poultry meat'],
        ['HamIcon', '🥓🍖', 'ham bacon pork meat'],
        ['SausageIcon', '🌭🥓', 'sausage hot dog bratwurst'],
        ['Hamburger01Icon', '🍔', 'hamburger burger cheeseburger fast food'],
        ['FrenchFries01Icon', '🍟', 'french fries chips fast food'],
        ['Pizza01Icon', '🍕', 'pizza slice italian pepperoni'],
        ['HotdogIcon', '🌭', 'hot dog frankfurter sausage'],
        ['SandwichIcon', '🥪🥙🧆', 'sandwich stuffed flatbread sub lunch falafel wrap pita'],
        ['Taco01Icon', '🌮🌯🫔', 'taco burrito tamale mexican wrap'],
        ['EggFriedIcon', '🍳', 'cooking fried egg breakfast pan'],
        ['Pan01Icon', '🥘🍳', 'shallow pan of food frying pan cook'],
        ['CookingPotIcon', '🍲🫕', 'pot of food stew fondue cooking'],
        ['Pot01Icon', '🍲🍯', 'pot cooking vessel'],
        ['PopcornIcon', '🍿', 'popcorn movie snack cinema'],
        [
            'RiceBowl01Icon',
            '🍚🍙🍘🍱🍛🥡',
            'cooked rice ball cracker bento curry bowl takeout box oyster pail leftovers',
        ],
        ['NoodlesIcon', '🍜🍲', 'steaming bowl noodles ramen soup'],
        ['SpaghettiIcon', '🍝', 'spaghetti pasta italian noodles'],
        ['SoupIcon', '🍲🥣', 'soup bowl with spoon broth'],
        ['Sushi01Icon', '🍣🍥', 'sushi fish cake sashimi japanese'],
        ['DimSum01Icon', '🥟🥠', 'dumpling dim sum fortune cookie'],
        ['PrawnIcon', '🍤🦐', 'fried shrimp prawn tempura'],
        ['IceCream01Icon', '🍨🍦', 'ice cream soft serve dessert'],
        ['IceCreamConeIcon', '🍦', 'ice cream cone soft serve'],
        ['IceCreamBowlIcon', '🍨🍧', 'ice cream bowl shaved ice sundae'],
        ['PopsicleIcon', '🍡🍧', 'popsicle ice lolly dango frozen'],
        ['DonutIcon', '🍩', 'doughnut donut sweet glazed'],
        ['CookieIcon', '🍪', 'cookie biscuit sweet'],
        ['BiscuitIcon', '🍪', 'biscuit cookie cracker'],
        ['CakeIcon', '🎂🍰', 'birthday cake shortcake dessert celebrate'],
        ['BirthdayCakeIcon', '🎂', 'birthday cake candles celebration party'],
        ['CakeSliceIcon', '🍰🥮', 'cake slice shortcake moon cake'],
        ['Cupcake01Icon', '🧁', 'cupcake muffin dessert sweet'],
        ['PieIcon', '🥧', 'pie dessert slice pastry'],
        ['ApplePieIcon', '🥧🍎', 'apple pie dessert baked'],
        ['DessertIcon', '🍮🍨', 'dessert custard pudding sweet'],
        ['ChocolateIcon', '🍫', 'chocolate bar cocoa sweet'],
        ['CandyIcon', '🍬🍭', 'candy sweets lollipop sugar'],
        ['CandyCaneIcon', '🍬🎄', 'candy cane christmas peppermint'],
        ['LollipopIcon', '🍭', 'lollipop candy sucker sweet'],
        ['CottonCandyIcon', '🍬', 'cotton candy floss fair sweet'],
        ['YogurtIcon', '🍦🥛', 'yogurt dairy cup snack'],
        ['MilkIcon', '🥛🍼', 'glass of milk baby bottle dairy'],
        ['MilkBottleIcon', '🍼🥛', 'baby bottle milk feeding'],
        ['Coffee01Icon', '☕', 'hot beverage coffee espresso caffeine cafe'],
        ['CoffeeBeansIcon', '☕🫘', 'coffee beans roast espresso'],
        ['TeaIcon', '🍵🫖🧉', 'teacup tea green brew mate yerba gourd'],
        ['TeaPodIcon', '🫖🍵', 'teapot tea brew kettle'],
        ['BubbleTea01Icon', '🧋', 'bubble tea boba milk tea'],
        ['BeerIcon', '🍺🍻', 'beer mug clinking pint pub ale'],
        [
            'DrinkIcon',
            '🍸🍹🥃🍷🍶🥂🍾🫗',
            'cocktail glass tropical drink tumbler wine sake toast bottle with popping cork champagne pouring liquid pour',
        ],
        ['SodaCanIcon', '🥤🧃🥫', 'cup with straw soda beverage box canned food'],
        ['SoftDrink01Icon', '🥤🧃', 'soft drink soda beverage'],
        ['CupSodaIcon', '🥤', 'cup with straw soda fountain drink'],
        ['IceCubesIcon', '🧊', 'ice cubes frozen cold'],
        ['JarIcon', '🫙🍯🧂', 'jar container honey preserve salt shaker seasoning spice'],
        ['AmphoraIcon', '🏺', 'amphora vase ancient vessel'],
        ['BbqGrillIcon', '🍖🔥', 'bbq grill barbecue cookout'],
        ['ChopsticksIcon', '🥢', 'chopsticks asian utensils'],
        ['UtensilsIcon', '🍴🍽️', 'fork and knife utensils cutlery eat dining'],
        ['SpoonAndForkIcon', '🍴🥄', 'spoon and fork cutlery dining'],
        ['SpoonIcon', '🥄', 'spoon cutlery scoop'],
        ['ForkIcon', '🍴', 'fork cutlery eat'],
        ['Knife01Icon', '🔪🗡️', 'kitchen knife blade chop dagger'],
        ['KnivesIcon', '🔪⚔️', 'knives blades crossed'],
        ['PlateIcon', '🍽️🥘', 'plate dish dinnerware serving'],
        ['Dish01Icon', '🍽️🥘', 'dish meal serving plate'],
        ['ServingFoodIcon', '🍽️🤵', 'serving food waiter restaurant service'],
        ['RestaurantIcon', '🍽️🏪', 'restaurant dining eatery menu'],
        ['MenuRestaurantIcon', '📜🍽️', 'restaurant menu dining list'],
        ['StreetFoodIcon', '🌮🍢', 'street food stall vendor oden'],
        ['ChefHatIcon', '👨‍🍳🍳', 'chef hat toque cooking kitchen'],
        ['KitchenUtensilsIcon', '🍴🥄', 'kitchen utensils cookware tools'],
        ['WhiskIcon', '🥣🍰', 'whisk mixing baking'],
        ['RollingPinIcon', '🥖🍪', 'rolling pin dough baking'],
        ['SpatulaIcon', '🍳🥞', 'spatula flip cooking'],
        ['Napkins01Icon', '🧻🍽️', 'napkins tissue serviette table'],
    ],
    Work: [
        ['AddressBookIcon', '📇', 'card index contacts rolodex directory'],
        ['Briefcase01Icon', '💼', 'briefcase work business office job portfolio'],
        ['Folder01Icon', '📁🗂️', 'file folder card index dividers directory'],
        ['FolderOpenIcon', '📂', 'open file folder browse directory'],
        ['File01Icon', '📄📃', 'page facing up document file page with curl'],
        ['FileTextIcon', '📄📝', 'document text memo note write'],
        ['NoteIcon', '📝🗒️', 'memo note spiral notepad write'],
        ['NotebookIcon', '📓📔📒', 'notebook journal decorative cover ledger accounts record book'],
        ['Calendar01Icon', '📅📆🗓️', 'calendar date schedule spiral tear off'],
        ['CalendarDaysIcon', '📅', 'calendar days month agenda'],
        ['ClipboardIcon', '📋', 'clipboard list checklist notes'],
        ['ChartIcon', '📊📈', 'bar chart increasing analytics graph statistics'],
        ['ChartDecreaseIcon', '📉', 'chart decreasing downward trend loss'],
        ['ChartIncreaseIcon', '📈💹', 'chart increasing upward trend growth yen'],
        ['PieChartIcon', '📊🥧', 'pie chart share breakdown proportion'],
        ['PinIcon', '📌📍', 'pushpin round pushpin pin location marker'],
        ['PaperclipIcon', '📎🖇️', 'paperclip attachment linked clips'],
        ['AttachmentIcon', '📎', 'attachment file clip attach'],
        ['RulerIcon', '📏📐', 'straight ruler triangular measure'],
        ['ScissorsIcon', '✂️', 'scissors cut snip trim'],
        ['TrashIcon', '🗑️', 'wastebasket trash bin delete garbage'],
        ['ArchiveIcon', '🗃️🗄️', 'card file box file cabinet archive storage'],
        ['Cabinet01Icon', '🗄️', 'file cabinet drawer storage'],
        ['Mail01Icon', '✉️📧📨', 'envelope email e-mail incoming message letter'],
        ['MailSend01Icon', '📤📩', 'outbox tray envelope with arrow send outgoing'],
        ['MailReceive01Icon', '📥', 'inbox tray receive incoming mail'],
        ['InboxIcon', '📥📬', 'inbox tray mailbox received messages'],
        ['MailboxIcon', '📫📪📬📭📮', 'mailbox postbox closed open raised lowered flag post'],
        ['MailOpenIcon', '📖📬', 'open mail envelope read message'],
        ['PackageIcon', '📦', 'package parcel box shipping delivery'],
        ['Megaphone01Icon', '📢📣', 'loudspeaker megaphone announce broadcast shout'],
        ['BellIcon', '🔔🎐', 'bell notification alert ring reminder wind chime breeze'],
        ['BellOffIcon', '🔕', 'bell with slash mute notifications off silent'],
        ['Task01Icon', '📋✅', 'task todo checklist item done'],
        ['CheckListIcon', '📋☑️', 'check list todo tasks tick'],
        ['ListTodoIcon', '📝☑️', 'todo list tasks checklist'],
        ['KanbanIcon', '📋🗂️', 'kanban board columns workflow'],
        ['Target01Icon', '🎯', 'bullseye target goal aim dart'],
        ['GoalIcon', '🎯⛳', 'goal target objective flag in hole'],
        ['MilestoneIcon', '🚩🏁', 'milestone marker checkpoint flag'],
        [
            'Flag01Icon',
            '🚩🏳️🏴🏁🎌',
            'flag white black chequered marker crossed flags japan celebration',
        ],
        ['RacingFlagIcon', '🏁', 'chequered flag finish race'],
        ['Tag01Icon', '🏷️🔖', 'label tag bookmark price'],
        ['Bookmark01Icon', '🔖📑', 'bookmark tabs save mark'],
        ['StickyNote01Icon', '🗒️📝', 'sticky note memo reminder post it'],
        ['SignatureIcon', '✍️🖋️', 'signature writing hand sign autograph'],
        ['StampIcon', '📮🏷️', 'stamp postmark approve seal'],
        ['ContractsIcon', '📜📄', 'contract agreement document scroll terms'],
        ['InvoiceIcon', '🧾💵', 'invoice bill statement charge'],
        ['ReceiptIcon', '🧾', 'receipt proof purchase bill'],
        ['Presentation01Icon', '📊🎤', 'presentation slides deck talk'],
        ['HourglassIcon', '⌛⏳', 'hourglass sand timer waiting elapsed'],
        [
            'Clock01Icon',
            '🕐🕑🕒🕓🕔🕕🕖🕗🕘🕙🕚🕛🕰️🕧🕜🕝🕞🕟🕠🕡🕢🕣🕤🕥🕦',
            'clock time hour oclock mantelpiece half past thirty',
        ],
        ['AlarmClockIcon', '⏰', 'alarm clock wake ring reminder'],
        ['StopWatchIcon', '⏱️⏲️', 'stopwatch timer clock elapsed'],
        ['Timer01Icon', '⏲️⏱️', 'timer countdown clock'],
        ['Watch01Icon', '⌚', 'watch wristwatch time wearable'],
        ['WorkIcon', '💼🏢', 'work job office employment career'],
        ['VoteIcon', '🗳️', 'ballot box vote election poll'],
        ['BalanceScaleIcon', '⚖️', 'balance scale justice fairness weigh law'],
        ['GavelIcon', '⚖️🔨', 'gavel judge court verdict law'],
        ['IdCardIcon', '🪪📛', 'identification card id name badge'],
        ['Certificate01Icon', '📜🎖️', 'certificate diploma award credential'],
    ],
    Tech: [
        ['SmartPhone01Icon', '📱📲📟', 'mobile phone smartphone cell device pager beeper'],
        ['TelephoneIcon', '☎️📞', 'telephone receiver landline call phone'],
        ['CallIcon', '📞📱', 'call phone dial ring'],
        ['LaptopIcon', '💻', 'laptop notebook computer macbook'],
        ['ComputerIcon', '🖥️💻', 'desktop computer monitor pc workstation'],
        ['MonitorIcon', '🖥️📺', 'monitor display screen television'],
        ['PrinterIcon', '🖨️📠', 'printer print paper output fax machine document send'],
        ['KeyboardIcon', '⌨️', 'keyboard typing keys input'],
        ['Mouse01Icon', '🖱️🖲️', 'computer mouse trackball pointer input'],
        ['BatteryFullIcon', '🔋', 'battery full charge power'],
        ['BatteryLowIcon', '🪫', 'low battery empty charge power'],
        ['PlugSocketIcon', '🔌', 'electric plug socket power outlet'],
        ['FloppyDiskIcon', '💾', 'floppy disk save diskette storage'],
        ['DiscIcon', '💿📀💽', 'optical disk dvd cd computer disk'],
        ['AbacusIcon', '🧮', 'abacus counting arithmetic calculate'],
        ['CameraVideoIcon', '🎥📹', 'movie camera video camera film record'],
        [
            'Camera01Icon',
            '📷📸🤳',
            'camera photo picture flash snapshot selfie self portrait front',
        ],
        ['FilmRoll01Icon', '🎞️📽️', 'film frames projector reel strip'],
        ['ClapperboardIcon', '🎬', 'clapper board film slate action director'],
        ['Tv01Icon', '📺', 'television tv screen broadcast'],
        ['VideotapeIcon', '📼', 'videocassette vhs tape recording'],
        ['Search01Icon', '🔍🔎', 'magnifying glass search find look zoom'],
        ['SatelliteIcon', '🛰️📡', 'satellite antenna dish space signal'],
        ['Radar01Icon', '📡🛰️', 'radar scan detect signal'],
        ['AntennaIcon', '📶📡', 'antenna bars signal reception'],
        ['SignalIcon', '📶', 'antenna bars signal reception strength'],
        ['WirelessIcon', '🛜📶', 'wireless wifi network connection'],
        ['Wifi01Icon', '🛜📶', 'wifi wireless internet network'],
        ['VibrateIcon', '📳', 'vibration mode buzz haptics'],
        ['AirplaneModeIcon', '📴✈️', 'mobile phone off airplane mode offline'],
        [
            'TestTubeIcon',
            '🧪⚗️🧫',
            'test tube alembic experiment chemistry lab petri dish culture biology',
        ],
        ['MicroscopeIcon', '🔬', 'microscope lab research science'],
        ['Telescope01Icon', '🔭', 'telescope astronomy stargaze observe'],
        ['Atom01Icon', '⚛️', 'atom symbol science physics nuclear'],
        ['MagnetIcon', '🧲', 'magnet attract magnetic force pull'],
        ['RadiationIcon', '☢️', 'radioactive radiation nuclear hazard'],
        ['BiohazardIcon', '☣️', 'biohazard contamination danger biological'],
        ['RocketIcon', '🚀', 'rocket launch ship space startup'],
        ['UfoIcon', '🛸👽', 'flying saucer ufo alien spacecraft'],
        ['SpaceshipIcon', '🚀🛸', 'spaceship rocket spacecraft'],
    ],
    Travel: [
        ['Car01Icon', '🚗🚘🚙🏎️', 'automobile car sport utility vehicle racing suv'],
        ['TaxiIcon', '🚕🚖', 'taxi cab ride hail'],
        ['PoliceCarIcon', '🚓🚔🚨', 'police car light siren patrol'],
        ['AmbulanceIcon', '🚑', 'ambulance emergency medical siren'],
        ['Bus01Icon', '🚌🚍🚎🚐', 'bus trolleybus minibus oncoming coach'],
        ['SchoolBusIcon', '🚌🏫', 'school bus student transport'],
        ['TruckIcon', '🚚🚛🛻', 'delivery truck articulated lorry pickup haul'],
        ['TruckDeliveryIcon', '🚚📦', 'delivery truck shipping courier'],
        [
            'Train01Icon',
            '🚂🚆🚄🚅🚈🚝🚞',
            'locomotive train high speed bullet light rail monorail railway',
        ],
        ['TramIcon', '🚊🚋🚃', 'tram streetcar railway car trolley'],
        ['MetroIcon', '🚇🚉', 'metro subway underground station'],
        ['SpeedTrain01Icon', '🚄🚅', 'high speed train bullet shinkansen express'],
        ['TrainTrackIcon', '🛤️', 'railway track rails line'],
        ['Motorbike01Icon', '🏍️🛵', 'motorcycle motor scooter moped ride'],
        ['Scooter01Icon', '🛴🛵🛺', 'kick scooter motor ride auto rickshaw tuk three wheeler'],
        ['BicycleIcon', '🚲🚴🚵', 'bicycle bike cycling mountain biking'],
        ['RollerSkateIcon', '🛼⛸️🛹', 'roller skate ice rink skateboard board street'],
        ['CableCarIcon', '🚠🚡🚟', 'aerial tramway mountain cableway suspension railway gondola'],
        ['RoadIcon', '🛣️🚏', 'motorway road highway bus stop street'],
        ['TrafficLightIcon', '🚦🚥', 'traffic light signal stop go'],
        ['TrafficConeIcon', '🚧', 'construction traffic cone roadwork barrier'],
        ['ConstructionIcon', '🚧🏗️', 'construction building site crane works'],
        ['StopIcon', '🛑', 'stop sign halt octagon'],
        ['CarParking01Icon', '🅿️🚗', 'parking p button car park'],
        ['FuelStationIcon', '⛽', 'fuel pump gas station petrol'],
        ['OilBarrelIcon', '🛢️', 'oil drum barrel petroleum fuel'],
        ['TireIcon', '🛞', 'wheel tire tyre rim'],
        ['AnchorIcon', '⚓', 'anchor nautical harbor ship'],
        ['LifebuoyIcon', '🛟🆘', 'ring buoy life preserver rescue help sos emergency distress'],
        ['SailboatIcon', '⛵🛶', 'sailboat canoe kayak boat sailing'],
        ['BoatIcon', '🚤🛥️', 'speedboat motor boat watercraft'],
        ['ShipIcon', '🚢🛳️', 'ship passenger cruise vessel'],
        ['FerryBoatIcon', '⛴️', 'ferry boat crossing passenger'],
        ['Airplane01Icon', '✈️🛩️', 'airplane plane flight small aircraft'],
        ['AirplaneTakeOff01Icon', '🛫', 'airplane departure take off flight'],
        ['AirplaneLanding01Icon', '🛬', 'airplane arrival landing flight'],
        ['ParaglidingIcon', '🪂', 'parachute paragliding skydive'],
        ['HelicopterIcon', '🚁', 'helicopter chopper rotor'],
        ['Luggage01Icon', '🧳🛄🛅', 'luggage suitcase baggage claim travel left locker storage'],
        ['HotelBellIcon', '🛎️', 'bellhop bell hotel service reception'],
        ['PassportIcon', '🛂📘🛃', 'passport control travel border immigration customs declare'],
        ['CompassIcon', '🧭', 'compass navigation direction bearing'],
        ['MapsIcon', '🗺️🗾', 'world map map of japan atlas geography'],
        ['Location01Icon', '📍🗺️', 'location pin map marker place'],
        ['House01Icon', '🏠🏡🏘️', 'house home with garden houses residence'],
        ['Home01Icon', '🏠🏡', 'home house residence dwelling'],
        ['HutIcon', '🛖⛺', 'hut tent shelter cabin'],
        ['TentIcon', '⛺🏕️🎪', 'tent camping circus tent campsite'],
        ['CampfireIcon', '🏕️🔥', 'campfire camping bonfire outdoors'],
        ['ApartmentIcon', '🏢🏬', 'office building apartment department store block'],
        ['OfficeIcon', '🏢🏣🏤', 'office building post office workplace'],
        ['BuildingIcon', '🏢🏗️', 'building tower structure'],
        ['Hospital01Icon', '🏥', 'hospital clinic medical center'],
        ['BankIcon', '🏦', 'bank finance vault branch'],
        ['Hotel01Icon', '🏨🏩', 'hotel love hotel lodging stay'],
        ['Store01Icon', '🏪🏬🏚️', 'convenience store department shop derelict house'],
        ['SchoolIcon', '🏫', 'school education campus classroom'],
        ['UniversityIcon', '🏛️🎓', 'university classical building college academy'],
        ['FactoryIcon', '🏭', 'factory plant industry manufacturing'],
        ['CastleIcon', '🏰🏯', 'castle japanese castle fortress palace'],
        ['ChurchIcon', '⛪✝️', 'church chapel cross christian'],
        ['Mosque01Icon', '🕌☪️', 'mosque islam masjid star and crescent'],
        ['ChinaTempleIcon', '🛕⛩️', 'hindu temple shinto shrine torii'],
        ['TorriGateIcon', '⛩️', 'shinto shrine torii gate japan'],
        ['Kaaba01Icon', '🕋', 'kaaba mecca hajj islam'],
        ['City01Icon', '🏙️🌃🌆', 'cityscape skyline night with stars downtown dusk'],
        ['BridgeIcon', '🌉🌁', 'bridge at night span crossing'],
        ['EiffelTowerIcon', '🗼🇫🇷', 'tokyo tower eiffel landmark monument'],
        ['WashingtonMonumentIcon', '🗽🏛️', 'statue of liberty new york landmark monument obelisk'],
        ['PlazaIcon', '⛲', 'fountain water plaza park'],
        ['FerrisWheelIcon', '🎡', 'ferris wheel fair amusement park'],
        ['RollerCoasterIcon', '🎢', 'roller coaster amusement park thrill'],
        ['SeesawIcon', '🛝⚖️', 'playground slide seesaw park play'],
        ['FootballPitchIcon', '🏟️', 'stadium arena venue crowd'],
        ['HotTubeIcon', '♨️🛁', 'hot springs onsen spa steam'],
        ['ChairBarberIcon', '💈', 'barber pole shop haircut salon'],
    ],
    Finance: [
        ['Money01Icon', '💰💵💴💶💷🤑', 'money cash banknote dollar yen euro pound bag rich'],
        ['MoneyBag01Icon', '💰', 'money bag savings wealth funds'],
        ['Coins01Icon', '🪙💰', 'coin coins change currency'],
        ['BanknoteIcon', '💵💴💶💷', 'banknote bill cash dollar yen euro pound'],
        ['MoneySend01Icon', '💸', 'money with wings send spend transfer payment'],
        ['CreditCardIcon', '💳', 'credit card debit payment pay'],
        ['SafeBoxIcon', '🪎🔐', 'treasure chest safe vault strongbox'],
        ['VaultIcon', '🏦🔐', 'vault safe secure storage bank'],
        ['CurrencyIcon', '💱💲', 'currency exchange dollar sign money conversion'],
        ['Exchange01Icon', '💱🔄', 'currency exchange swap convert trade'],
        ['DollarSignIcon', '💲💵', 'dollar sign money usd currency'],
        ['ShoppingCart01Icon', '🛒', 'shopping cart trolley basket buy checkout'],
        ['ShoppingBasket01Icon', '🧺🛒', 'shopping basket groceries buy'],
        ['ShoppingBag01Icon', '🛍️👜', 'shopping bags handbag purchase retail'],
        [
            'GiftIcon',
            '🎁🧧🎅🤶🧑‍🎄',
            'wrapped gift present red envelope birthday santa claus christmas father mrs mx holiday',
        ],
        ['GiftCardIcon', '🎁💳', 'gift card voucher present'],
        ['Coupon01Icon', '🎟️🏷️', 'coupon voucher admission ticket discount'],
        ['DiscountIcon', '🏷️💸', 'discount sale percent off deal'],
        ['BarcodeIcon', '📊🏷️', 'barcode scan product sku'],
        ['QrCodeIcon', '🔳📱', 'qr code scan square link'],
        ['Atm01Icon', '🏧', 'atm sign cash machine withdraw bank'],
        ['GoldIngotsIcon', '🥇💰', 'gold ingots bullion bars wealth'],
        ['AuctionIcon', '⚖️🔨', 'auction bid hammer gavel sale'],
    ],
    Health: [
        ['SyringeIcon', '💉', 'syringe injection vaccine shot needle'],
        ['VaccineIcon', '💉🩹', 'vaccine immunization shot dose'],
        ['PillIcon', '💊', 'pill medicine capsule tablet drug'],
        ['PillsTabletIcon', '💊', 'pills tablets medication dose'],
        ['BandageIcon', '🩹🤕', 'adhesive bandage plaster band aid injury'],
        ['StethoscopeIcon', '🩺', 'stethoscope doctor exam checkup'],
        ['XRayIcon', '🩻', 'x-ray radiograph scan bones'],
        ['BloodIcon', '🩸', 'drop of blood donation bleeding type'],
        ['GiveBloodIcon', '🩸❤️', 'give blood donation donate'],
        ['FirstAidKitIcon', '🩹⛑️', 'first aid kit emergency medical rescue helmet'],
        ['Medicine01Icon', '💊🏥', 'medicine pharmacy drug treatment'],
        ['CaduceusIcon', '⚕️', 'medical symbol caduceus healthcare'],
        ['HealthIcon', '❤️‍🩹⚕️', 'health wellness care medical'],
        ['HeartPulseIcon', '💓🫀', 'heartbeat pulse cardio vitals'],
        ['Dumbbell01Icon', '🏋️🏋️‍♀️', 'dumbbell weights lifting gym workout'],
        ['KettlebellIcon', '🏋️💪', 'kettlebell weight strength gym'],
        ['WeightScaleIcon', '⚖️🏋️', 'weight scale bathroom measure body'],
        ['Treadmill01Icon', '🏃🏋️', 'treadmill running cardio gym'],
        ['HandSanitizerIcon', '🧴🧼', 'hand sanitizer lotion bottle disinfect'],
        ['ShowerHeadIcon', '🚿', 'shower head bathe wash'],
        [
            'Toilet01Icon',
            '🚽🚾🪠🚹🚺🚻',
            'toilet restroom water closet lavatory plunger unclog mens room womens bathroom',
        ],
        ['PerfumeIcon', '🧴💐', 'perfume fragrance scent cologne'],
        ['CigaretteIcon', '🚬🚭', 'cigarette smoking no smoking tobacco'],
        [
            'WheelchairIcon',
            '♿🦽🦼🩼',
            'wheelchair accessible mobility disabled crutch injury support',
        ],
    ],
    Sports: [
        ['FrisbeeIcon', '🥏', 'flying disc frisbee throw catch'],
        ['StarAward01Icon', '💯', 'hundred points perfect score full marks award'],
        ['FootballIcon', '⚽', 'soccer ball football pitch goal'],
        ['AmericanFootballIcon', '🏈🏉', 'american football rugby gridiron'],
        ['Basketball01Icon', '🏀⛹️', 'basketball hoop dribble court'],
        ['BaseballIcon', '⚾🥎', 'baseball softball bat pitch'],
        ['VolleyballIcon', '🏐🤽', 'volleyball water polo serve'],
        ['TennisBallIcon', '🎾', 'tennis ball court serve'],
        ['TennisRacketIcon', '🎾🏸', 'tennis racket racquet badminton'],
        ['BadmintonIcon', '🏸', 'badminton shuttlecock racquet'],
        ['CricketBatIcon', '🏏', 'cricket game bat wicket'],
        ['HockeyIcon', '🏒🏑🥍', 'ice hockey field stick puck lacrosse crosse'],
        ['IceHockeyIcon', '🏒🥅', 'ice hockey rink goal net'],
        ['GolfBallIcon', '⛳🏌️', 'golf ball flag in hole tee course'],
        ['BowlingIcon', '🎳', 'bowling pins strike alley'],
        ['Billiard01Icon', '🎱🪀', 'pool 8 ball billiards snooker'],
        ['TableTennisBatIcon', '🏓', 'ping pong table tennis paddle'],
        ['BoxingGloveIcon', '🥊🥋', 'boxing glove punch fight martial arts uniform gi karate judo'],
        ['PunchIcon', '🥊👊🤼', 'punch boxing hit fight wrestling grapple wrestle'],
        ['FencingIcon', '🤺🗡️', 'fencing foil sword duel'],
        ['SwimmingIcon', '🏊🤽', 'swimming swim pool water polo'],
        ['SurfboardIcon', '🏄🏄‍♀️', 'surfing surfboard wave beach'],
        ['SkiIcon', '⛷️🎿🏂🛷', 'skier skis snowboard slope winter sled sledge toboggan'],
        ['IceSkatingIcon', '⛸️', 'ice skate figure skating rink'],
        ['CurlingIcon', '🥌', 'curling stone ice sport'],
        ['ArcherIcon', '🏹🎯', 'bow and arrow archery aim target'],
        ['DartIcon', '🎯🎪', 'dart bullseye throw target'],
        ['FishingRodIcon', '🎣', 'fishing pole rod angling catch'],
        ['FinsIcon', '🤿🏊', 'diving mask fins snorkel scuba'],
        ['KayakIcon', '🛶🚣', 'kayak canoe rowing paddle'],
        ['TrophyIcon', '🏆🥇', 'trophy cup champion winner first place'],
        ['Medal01Icon', '🏅🎖️🥇🥈🥉', 'sports medal military first second third place award'],
        ['ChampionIcon', '🏆🥇', 'champion winner victory title'],
        ['PodiumIcon', '🥇🏆', 'podium winners rank ceremony'],
        ['WhistleIcon', '📣🏁', 'whistle referee foul signal'],
        ['GameController01Icon', '🎮🕹️', 'video game controller gamepad joystick console'],
        ['Joystick01Icon', '🕹️', 'joystick arcade retro game'],
        ['DiceIcon', '🎲🎰', 'game die dice slot machine chance roll'],
        ['PuzzleIcon', '🧩', 'puzzle piece jigsaw solve'],
        ['Chess01Icon', '♟️🏁', 'chess pawn board strategy'],
        ['ChessPawnIcon', '♟️', 'chess pawn piece'],
        ['Cards01Icon', '🃏🎴🀄', 'playing cards joker mahjong flower deck'],
        ['SpadesIcon', '♠️', 'spade suit cards'],
        ['Clubs01Icon', '♣️', 'club suit cards clover'],
        ['DiamondIcon', '♦️🔶🔷💎', 'diamond suit gem jewel large blue orange'],
        ['GemIcon', '💎', 'gem stone diamond jewel precious'],
        ['ToyBrickIcon', '🧸🪆', 'toy brick blocks lego nesting dolls teddy bear plush stuffed'],
        ['KiteIcon', '🪁', 'kite fly wind string'],
        ['TrampolineIcon', '🤸🎪', 'trampoline bounce jump'],
        ['SkippingRopeIcon', '🤸🏃', 'skipping rope jump exercise'],
        ['PokeballIcon', '🎮⚪', 'pokeball game catch'],
        ['RubiksCubeIcon', '🧩🎲', 'rubiks cube puzzle twist'],
        ['TicTacToeIcon', '⭕❌', 'tic tac toe noughts crosses grid'],
        ['GymnasticRingsIcon', '🤸🏅', 'gymnastic rings gymnastics apparatus'],
    ],
    Arts: [
        [
            'MusicNote01Icon',
            '🎵🎶🎷🎺🪊🪈🪗',
            'musical note notes song melody tune saxophone trumpet trombone brass horn flute woodwind pipe recorder accordion squeezebox folk',
        ],
        ['MusicIcon', '🎼🎵🎹', 'music musical score sheet composition keyboard piano keys synth'],
        ['GuitarIcon', '🎸🪕🎻🪉', 'guitar banjo strings strum violin fiddle harp orchestra'],
        ['DrumIcon', '🥁🪘🪇', 'drum long drum maracas percussion beat'],
        ['MetronomeIcon', '🎼🥁', 'metronome tempo beat rhythm'],
        ['Mic01Icon', '🎤🎙️', 'microphone studio mic voice sing'],
        ['HeadphonesIcon', '🎧', 'headphone headphones listen audio'],
        ['RadioIcon', '📻📯', 'radio broadcast postal horn tune'],
        ['SpeakerIcon', '🔊🔈🔉', 'speaker volume loud sound audio'],
        ['VolumeMute01Icon', '🔇', 'muted speaker mute silence volume off'],
        ['VolumeHighIcon', '🔊', 'speaker high volume loud'],
        ['VolumeLowIcon', '🔈🔉', 'speaker low medium volume quiet'],
        ['AudioWave01Icon', '🎵〰️', 'audio wave sound waveform level slider'],
        ['MixerIcon', '🎛️🎚️', 'control knobs level slider mixer audio'],
        ['TurntableIcon', '🎧💿', 'turntable dj vinyl deck'],
        ['Vynil01Icon', '💿📀', 'vinyl record album lp'],
        ['DiscAlbumIcon', '💿📀', 'disc album record music'],
        ['CassetteTapeIcon', '📼🎵', 'cassette tape mixtape audio'],
        ['PaletteIcon', '🎨', 'artist palette paint colors art'],
        ['PaintBrush01Icon', '🖌️🎨', 'paintbrush paint art brush'],
        ['PaintBucketIcon', '🎨🪣', 'paint bucket fill color'],
        ['PencilIcon', '✏️', 'pencil write draw sketch'],
        ['Pen01Icon', '🖊️🖋️✒️', 'pen fountain pen black nib write ink'],
        ['QuillWrite01Icon', '🪶✍️', 'quill feather pen write ink calligraphy'],
        ['HighlighterIcon', '🖍️🖊️', 'highlighter marker crayon color'],
        ['EraserIcon', '🧽✏️', 'eraser rubber undo clean'],
        ['CanvasIcon', '🖼️🎨', 'canvas easel painting art'],
        ['FrameIcon', '🖼️', 'framed picture photo frame art'],
        ['Image01Icon', '🖼️📷', 'image picture photo framed'],
        ['MaskTheater01Icon', '🎭🎪', 'performing arts theater drama comedy masks'],
        ['DramaIcon', '🎭', 'drama theatre acting play'],
        ['TheaterIcon', '🎭🎦', 'theater cinema stage performance'],
        ['VenetianMaskIcon', '🎭🧿', 'venetian mask masquerade carnival'],
        ['Ticket01Icon', '🎫🎟️', 'ticket admission entry pass'],
        ['Book01Icon', '📕📗📘📙📓', 'book closed green blue orange notebook read'],
        ['BookOpen01Icon', '📖', 'open book read study pages'],
        ['Books01Icon', '📚', 'books library stack reading'],
        ['LibraryIcon', '📚🏛️', 'library books collection archive'],
        ['ScrollIcon', '📜🗞️', 'scroll parchment rolled up newspaper document'],
        ['NewsIcon', '📰🗞️', 'newspaper news press headlines'],
        ['ThreadIcon', '🧵🪢🪡', 'thread yarn spool knot sewing needle stitch tailor'],
        ['SpoolIcon', '🧵🧶', 'spool thread yarn bobbin'],
        ['OrigamiIcon', '🎎🪅', 'origami paper folding craft dolls'],
        ['StickerIcon', '🏷️✨', 'sticker decal label'],
        ['ColorsIcon', '🎨🌈', 'colors palette swatches hue'],
        ['ColorPickerIcon', '🎨💧', 'color picker eyedropper sample'],
    ],
    Objects: [
        ['Fan01Icon', '🪭', 'folding hand fan cooling breeze'],
        [
            'SquareIcon',
            '🟥🟧🟨🟩🟦🟪🟫⬛⬜🔲🔳',
            'square block red orange yellow green blue purple brown black white button',
        ],
        [
            'CircleIcon',
            '🔴🟠🟡🟢🔵🟣🟤⚫⚪🔘',
            'circle dot red orange yellow green blue purple brown black white radio button',
        ],
        // Clothing
        ['GlassesIcon', '👓🥽', 'glasses spectacles goggles eyewear'],
        ['TShirtIcon', '👕👚', 'tshirt shirt clothes top'],
        ['Shirt01Icon', '👔👕', 'shirt necktie dress shirt formal'],
        ['TieIcon', '👔', 'necktie tie formal suit'],
        ['BowTieIcon', '🎀👔', 'bow tie formal ribbon'],
        ['JoggerPantsIcon', '👖', 'jeans pants trousers denim'],
        ['ShortsPantsIcon', '🩳🩲', 'shorts briefs underwear'],
        ['Dress01Icon', '👗👘🥻', 'dress kimono sari gown'],
        ['HoodieIcon', '🧥👕', 'hoodie sweatshirt jumper'],
        ['JumpersIcon', '🧥🧣', 'jumper sweater coat pullover scarf winter neck warm'],
        ['CardiganIcon', '🧥', 'cardigan sweater knitwear'],
        ['GloveIcon', '🧤', 'gloves mittens hands warm'],
        ['SocksIcon', '🧦', 'socks hosiery feet'],
        ['TankTopIcon', '🎽🩱', 'tank top running shirt swimsuit'],
        ['SwimmingCapIcon', '🩱🏊', 'swimming cap swimsuit pool'],
        ['Underpants01Icon', '🩲👙', 'underpants briefs bikini underwear'],
        ['SandalsIcon', '🩴👡', 'sandals thong flip flops'],
        ['ShoesIcon', '👞👟🥿', 'shoe running shoe flat sneaker'],
        ['SneakerIcon', '👟', 'sneaker trainer running shoe'],
        ['RunningShoesIcon', '👟🏃', 'running shoes trainers jog'],
        ['ArmoredBootIcon', '🥾👢', 'hiking boot woman boot footwear'],
        ['HighHeels01Icon', '👠👡', 'high heeled shoe heels pumps'],
        ['HatIcon', '👒🎩🧢', 'hat top hat billed cap woman hat'],
        ['CapIcon', '🧢👲', 'cap billed baseball hat person with skullcap headwear'],
        ['GraduationCapIcon', '🎓', 'graduation cap mortarboard degree'],
        ['HardHatIcon', '⛑️🪖', 'helmet hard hat rescue worker military'],
        ['BulletproofVestIcon', '🦺🎽', 'safety vest high visibility protective'],
        ['HandBag01Icon', '👜👛👝', 'handbag purse clutch bag'],
        ['Backpack01Icon', '🎒', 'backpack rucksack school bag'],
        ['TravelBagIcon', '🧳🎒', 'travel bag luggage duffel'],
        ['HangerIcon', '🧥👔', 'hanger closet wardrobe clothes'],
        ['Wardrobe01Icon', '🚪🧥', 'wardrobe closet armoire clothes'],
        ['NecklaceIcon', '📿💎', 'necklace prayer beads jewelry chain'],
        ['EarRings01Icon', '💍💎', 'earrings jewelry accessory'],
        ['BlushBrush01Icon', '💄💋💅', 'lipstick makeup cosmetics nail polish manicure grooming'],
        ['HairClipsIcon', '🪮💇🪒', 'hair pick clips comb grooming razor shave blade'],
        ['BeltIcon', '👖🎽', 'belt buckle waist'],
        // Household
        ['DoorIcon', '🚪', 'door entrance exit doorway'],
        ['DoorLockIcon', '🚪🔒', 'door lock locked entrance secure'],
        ['Stairs01Icon', '🛗🪜', 'elevator lift floors ladder climb steps rungs'],
        ['MirrorIcon', '🪞', 'mirror reflection glass'],
        ['BlindsIcon', '🪟🪟', 'window blinds shades curtain'],
        ['CurtainsIcon', '🪟🎭', 'curtains drapes window'],
        ['Sofa01Icon', '🛋️', 'couch sofa lounge seat'],
        ['Chair01Icon', '🪑', 'chair seat furniture'],
        ['ArmchairIcon', '🛋️🪑', 'armchair lounge chair comfy'],
        ['RockingChairIcon', '🪑👵', 'rocking chair porch relax'],
        ['DiningTableIcon', '🍽️🪑', 'dining table furniture eat'],
        ['DeskIcon', '🪑💻', 'desk workspace table office'],
        ['PillowIcon', '🛏️😴', 'pillow cushion sleep bed'],
        ['ShelvingUnitIcon', '📚🗄️', 'shelving unit shelf storage'],
        ['BrushCleaningIcon', '🧹🧽', 'broom sweep clean witch sponge scrub wash'],
        ['TissuePaperIcon', '🧻', 'roll of paper toilet tissue'],
        ['BucketIcon', '🪣', 'bucket pail water clean'],
        ['DetergentIcon', '🧴🧼', 'detergent soap laundry clean'],
        ['ShampooIcon', '🧴🚿', 'shampoo lotion bottle hair'],
        ['BodySoapIcon', '🧼🧴🫧', 'body soap wash shower hygiene bubbles clean'],
        ['TowelsIcon', '🧻🛁', 'towels bath linen'],
        ['WashingMachineIcon', '🧺👕', 'washing machine laundry wash basket hamper carry'],
        ['VacuumCleanerIcon', '🧹🏠', 'vacuum cleaner hoover clean'],
        ['SafetyPin01Icon', '🧷', 'safety pin fasten diaper'],
        ['LampIcon', '💡🛋️', 'lamp light shade table'],
        ['LightbulbIcon', '💡', 'light bulb idea inspiration bright'],
        ['IdeaIcon', '💡✨', 'idea insight inspiration brainstorm'],
        ['FlashlightIcon', '🔦', 'flashlight torch beam light'],
        ['LanternIcon', '🏮🪔', 'red paper lantern diya lamp light'],
        // Tools
        ['HammerIcon', '🔨⚒️🛠️', 'hammer mallet tool build hammer and pick'],
        ['AxeIcon', '🪓', 'axe chop wood hatchet'],
        ['PickaxeIcon', '⛏️⚒️', 'pick pickaxe mine dig'],
        ['ShovelIcon', '🪏⛏️', 'shovel spade dig'],
        ['Wrench01Icon', '🔧🛠️', 'wrench spanner tool fix'],
        [
            'ToolsIcon',
            '🛠️🧰🪚🪛',
            'tools hammer and wrench toolbox repair carpentry saw screwdriver',
        ],
        ['ToolboxIcon', '🧰', 'toolbox tools kit repair'],
        ['Sword01Icon', '🗡️⚔️', 'dagger sword blade crossed swords'],
        ['SwordsIcon', '⚔️🔱', 'crossed swords battle fight duel trident emblem fork weapon'],
        ['Shield01Icon', '🛡️', 'shield protect defense guard security'],
        ['BombIcon', '💣💥', 'bomb explosive collision blast'],
        ['GunIcon', '🔫🪃', 'water pistol gun boomerang'],
        ['NutIcon', '🔩⚙️', 'nut and bolt screw hardware'],
        ['CogIcon', '⚙️', 'gear cog settings mechanism'],
        ['GearsIcon', '⚙️🔩', 'gears machinery settings cogs'],
        ['DrillIcon', '🔩🛠️', 'drill power tool bore'],
        ['LinkIcon', '🔗⛓️', 'link chain url connect chains'],
        ['Unlink01Icon', '⛓️‍💥🔗', 'broken chain unlink disconnect'],
        ['FishingHookIcon', '🪝🎣', 'hook fishing catch hang'],
        ['StraightEdgeIcon', '📏', 'straight edge ruler measure'],
        ['TapeMeasureIcon', '📏🗜️', 'tape measure clamp measure'],
        // Lock
        ['LockIcon', '🔒🔏', 'locked lock secure private closed'],
        ['LockOpenIcon', '🔓', 'unlocked open lock access'],
        ['Key01Icon', '🔑🗝️', 'key old key unlock access'],
        ['LockKeyIcon', '🔐', 'locked with key secure encrypted'],
        ['SecurityIcon', '🔐🛡️', 'security protection safety guard'],
        ['EncryptIcon', '🔐🔏', 'encrypt cipher secure lock'],
        // Symbols and other objects
        ['WandIcon', '🪄✨', 'magic wand spell sparkles'],
        ['MagicWand01Icon', '🪄🔮', 'magic wand enchant conjure'],
        ['PotionIcon', '🧪🔮', 'potion elixir brew flask crystal ball fortune predict mystic'],
        ['PumpkinIcon', '🎃', 'jack o lantern pumpkin halloween'],
        ['FireworksIcon', '🎆🎇🧨', 'fireworks sparkler firecracker celebrate'],
        ['BalloonIcon', '🎈', 'balloon party celebrate float'],
        ['BalloonsIcon', '🎈🎊', 'balloons party celebration'],
        ['PartyPopperIcon', '🎉🎊', 'party popper confetti ball celebrate congrats'],
        [
            'PartyIcon',
            '🥳🎉🧑‍🩰💃🕺👯🪩',
            'party celebration festive fun ballet dancer dancing dance bunny ears nightlife mirror ball disco glitter',
        ],
        [
            'GarlandsIcon',
            '🎊🎋🎏🎑',
            'garlands decoration streamers tanabata carp streamer moon viewing ceremony festival',
        ],
        ['RibbonIcon', '🎀🎗️', 'ribbon bow reminder awareness'],
        ['SignpostIcon', '🪧🛣️', 'placard sign protest board signpost direction marker'],
        ['LaurelWreath01Icon', '⚜️', 'fleur de lis heraldry emblem'],
        ['CrossIcon', '✝️☦️', 'latin cross orthodox christianity'],
        ['AllahIcon', '☪️🕌', 'allah islam star and crescent'],
        ['MuslimIcon', '🕌☪️', 'muslim islam faith prayer'],
        ['TasbihIcon', '📿', 'tasbih prayer beads rosary'],
        ['PrayerRug01Icon', '🕌🧎', 'prayer rug salah mat'],
        ['Infinity01Icon', '♾️', 'infinity endless loop forever'],
        ['CopyrightIcon', '©️', 'copyright legal rights'],
        ['RegisteredIcon', '®️', 'registered trademark legal'],
        ['TradeMarkIcon', '™️', 'trade mark tm brand'],
        ['UniversalAccessIcon', '♿', 'universal access accessibility inclusive'],
        [
            'AlertCircleIcon',
            '⚠️❗‼️⁉️❕',
            'warning alert exclamation caution danger question mark white',
        ],
        ['HelpCircleIcon', '❓❔', 'question mark help ask unknown'],
        ['InfoIcon', 'ℹ️', 'information info about details'],
        ['CheckmarkCircle01Icon', '✅☑️✔️', 'check mark button tick done approved'],
        ['CancelCircleIcon', '❌❎⛔🚫', 'cross mark prohibited no entry cancel forbidden'],
        [
            'BanIcon',
            '🚫⛔🙅🚸🚳🚯🚱🚷🔞',
            'ban prohibited forbidden no gesturing children crossing bicycles littering pedestrians non potable under eighteen',
        ],
        ['NoInternetIcon', '📵🚫', 'no mobile phones prohibited offline'],
        ['DangerIcon', '⚠️☢️', 'danger hazard warning risk'],
        ['SirenIcon', '🚨', 'police car light siren emergency alarm'],
        ['NewReleasesIcon', '🆕✨', 'new releases fresh badge'],
        ['ZodiacAriesIcon', '♈', 'aries zodiac ram astrology'],
        ['ZodiacTaurusIcon', '♉', 'taurus zodiac bull astrology'],
        ['ZodiacGeminiIcon', '♊', 'gemini zodiac twins astrology'],
        ['ZodiacCancerIcon', '♋', 'cancer zodiac crab astrology'],
        ['ZodiacLeoIcon', '♌', 'leo zodiac lion astrology'],
        ['ZodiacVirgoIcon', '♍', 'virgo zodiac maiden astrology'],
        ['ZodiacLibraIcon', '♎', 'libra zodiac scales astrology'],
        ['ZodiacScorpioIcon', '♏', 'scorpio zodiac scorpion astrology'],
        ['ZodiacSagittariusIcon', '♐', 'sagittarius zodiac archer astrology'],
        ['ZodiacCapricornIcon', '♑', 'capricorn zodiac goat astrology'],
        ['ZodiacAquariusIcon', '♒', 'aquarius zodiac water bearer astrology'],
        ['ZodiacPiscesIcon', '♓', 'pisces zodiac fish astrology'],
        ['ZodiacOphiuchusIcon', '⛎', 'ophiuchus zodiac serpent astrology'],
        ['VenusIcon', '♀️', 'female sign venus woman gender'],
        ['MarsIcon', '♂️', 'male sign mars man gender'],
        ['VenusAndMarsIcon', '⚧️♀️♂️🏳️‍⚧️', 'transgender symbol venus and mars gender flag trans pride'],
        ['NonBinaryIcon', '⚧️', 'non binary gender identity'],
    ],
};
